(() => {
'use strict';
const $=id=>document.getElementById(id),pw=window.PW;
const language=()=>{try{return localStorage.getItem('pw.language')||'ru'}catch{return'ru'}};
const copy={
ru:{title:'Достижения',desc:'Твои цели, значки и награды',note:'Награда за каждое достижение выдаётся один раз в текущей игре. Полный сброс закрывает достижения и начинает их прогресс заново.',all:'Все',ready:'Награды',earned:'Получены',locked:'В процессе',claim:'ЗАБРАТЬ',claimed:'✓ Получено',unlocked:'Достигнуто',loading:'Загружаю достижения…',error:'Не удалось загрузить достижения. Попробуй ещё раз.',retry:'ПОВТОРИТЬ',empty:'В этой категории пока нет достижений.',home:'НА ГЛАВНУЮ',categories:{main:'Главы',themes:'Темы',daily:'Загадка дня',duels:'Дуэли',challenges:'Испытания'},summary:(n,total,ready)=>`${n} / ${total} открыто · ${ready} наград ждут`,reward:n=>`Награда: ${n} монет`,network:'Не удалось подтвердить награду. Нажми «Забрать» снова — двойного начисления не будет.',lockedError:'Условие ещё не выполнено.'},
en:{title:'Achievements',desc:'Your goals, badges and rewards',note:'Each reward can be claimed once in the current game. A full reset clears achievements and starts their progress again.',all:'All',ready:'Rewards',earned:'Claimed',locked:'In progress',claim:'CLAIM',claimed:'✓ Claimed',unlocked:'Unlocked',loading:'Loading achievements…',error:'Could not load achievements. Try again.',retry:'RETRY',empty:'No achievements in this category yet.',home:'HOME',categories:{main:'Chapters',themes:'Themes',daily:'Daily puzzle',duels:'Duels',challenges:'Challenges'},summary:(n,total,ready)=>`${n} / ${total} unlocked · ${ready} rewards ready`,reward:n=>`Reward: ${n} coins`,network:'Could not confirm the reward. Tap Claim again — it will not be credited twice.',lockedError:'The goal is not complete yet.'},
az:{title:'Nailiyyətlər',desc:'Məqsədlərin, nişanların və mükafatların',note:'Hər mükafat cari oyunda yalnız bir dəfə verilir. Tam sıfırlama nailiyyətləri bağlayır və tərəqqini yenidən başladır.',all:'Hamısı',ready:'Mükafatlar',earned:'Alınıb',locked:'Davam edir',claim:'GÖTÜR',claimed:'✓ Alınıb',unlocked:'Açılıb',loading:'Nailiyyətlər yüklənir…',error:'Nailiyyətləri yükləmək olmadı. Yenidən cəhd et.',retry:'TƏKRARLA',empty:'Bu kateqoriyada hələ nailiyyət yoxdur.',home:'ANA SƏHİFƏ',categories:{main:'Fəsillər',themes:'Mövzular',daily:'Günün tapmacası',duels:'Duellər',challenges:'Sınaqlar'},summary:(n,total,ready)=>`${n} / ${total} açılıb · ${ready} mükafat hazırdır`,reward:n=>`Mükafat: ${n} sikkə`,network:'Mükafatı təsdiqləmək olmadı. Yenidən Götür düyməsinə toxun — iki dəfə hesablanmayacaq.',lockedError:'Şərt hələ yerinə yetirilməyib.'}
};
const t=()=>copy[language()]||copy.ru;
let itemLanguage=language(),items=[],filter='all',request=0,loading=false,claiming=new Set();
const active=()=>$('achievementsScreen').classList.contains('active');
function labels(){if(itemLanguage!==language()){items=[];itemLanguage=language()}const x=t();$('achievementsEntryTitle').textContent=x.title;$('achievementsEntryDesc').textContent=x.desc;$('profileAchievements').textContent='🏅 '+x.title+' ›';$('achievementsTitle').textContent=x.title;$('achievementsNote').textContent=x.note;$('achievementsHome').textContent=x.home;$('achievementsRetry').textContent=x.retry;$('achievementsBack').setAttribute('aria-label',x.home);paint()}
function element(tag,className,text){const e=document.createElement(tag);e.className=className;if(text!==undefined)e.textContent=text;return e}
function paint(){
 const x=t(),unlocked=items.filter(a=>a.unlocked).length,ready=items.filter(a=>a.unlocked&&!a.claimed).length;
 $('achievementsSummary').textContent=items.length?x.summary(unlocked,items.length,ready):'';
 $('achievementsEntryCount').textContent=items.length?`${unlocked} / ${items.length}`:'🏅';const badges=$('profileAchievementBadges');badges.replaceChildren();for(const a of items.filter(a=>a.unlocked).slice(-6)){const badge=element('span','',a.icon);badge.setAttribute('title',a.title);badge.setAttribute('aria-label',a.title);badges.append(badge)}
 const filters=$('achievementsFilters');filters.replaceChildren();for(const [id,label] of [['all',x.all],['ready',x.ready],...Object.entries(x.categories)]){const b=element('button',filter===id?'on':'',label);b.type='button';b.setAttribute('aria-pressed',String(filter===id));b.onclick=()=>{filter=id;paint()};filters.append(b)}
 const list=$('achievementsList');list.replaceChildren();const shown=items.filter(a=>filter==='all'||filter==='ready'&&a.unlocked&&!a.claimed||a.category===filter);
 if(!shown.length&&!loading)list.append(element('p','achievement-empty',x.empty));
 for(const a of shown){const card=element('article','achievement-card'+(a.unlocked?' unlocked':'')+(a.claimed?' claimed':''));card.append(element('span','achievement-icon',a.icon));const body=element('div','achievement-copy');body.append(element('h2','',a.title),element('p','',a.description));const progress=element('div','achievement-progress');progress.setAttribute('role','progressbar');progress.setAttribute('aria-valuenow',String(a.progress));progress.setAttribute('aria-valuemax',String(a.target));progress.setAttribute('aria-label',a.title);const bar=element('i','');bar.style.width=Math.min(100,a.progress/a.target*100)+'%';progress.append(bar);body.append(progress);const foot=element('div','achievement-foot');foot.append(element('small','',a.unlocked?x.unlocked:`${a.progress} / ${a.target}`),element('b','',`+${a.reward_coins} 🪙`));body.append(foot);
 if(a.unlocked){const b=element('button','achievement-claim',a.claimed?x.claimed:claiming.has(a.id)?'…':x.claim);b.type='button';b.disabled=a.claimed||claiming.size>0;b.onclick=()=>claim(a.id);body.append(b)}card.append(body);list.append(card)}
}
async function api(action,extra={}){const initData=window.Telegram?.WebApp?.initData||pw?.store?.get('pw.init','')||new URLSearchParams(location.hash.slice(1)).get('tgWebAppData')||new URLSearchParams(location.search).get('tgWebAppData')||'';const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch('https://bqoraxewpcnmidvjlpuy.supabase.co/functions/v1/achievements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,language:language(),initData,progressGeneration:pw?.player?.progress_generation,...extra}),signal:controller.signal});const j=await r.json();if(!r.ok){if(j.error==='progress_reset')await pw.login(true);throw new Error(j.error||'server_error');}return j}finally{clearTimeout(timeout)}}
function apply(j){window.PWFrames?.accept?.(j);itemLanguage=language();items=j.items||[];if(Number.isFinite(j.coins))document.querySelectorAll('[data-coins]').forEach(e=>e.textContent=String(j.coins));paint()}
async function load(){const token=++request;loading=true;paint();$('achievementsStatus').textContent=t().loading;$('achievementsRetry').hidden=true;try{await pw.login();const j=await api('state');if(token!==request||!active())return;apply(j);$('achievementsStatus').textContent=''}catch{if(token===request){$('achievementsStatus').textContent=t().error;$('achievementsRetry').hidden=false}}finally{if(token===request){loading=false;paint()}}}
async function claim(id){if(claiming.size)return;claiming.add(id);paint();const token=request;try{const j=await api('claim',{achievement:id});if(token===request&&active()){apply(j);$('achievementsStatus').textContent='';if(j.reward_coins>0)pw.sfx('coin');pw.login(true).catch(()=>{})}}catch(e){if(token===request&&active())$('achievementsStatus').textContent=e.message==='achievement_locked'?t().lockedError:t().network}finally{claiming.delete(id);if(active())paint()}}
function open(){filter='all';document.querySelectorAll('.modal').forEach(e=>e.hidden=true);document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('active',e.id==='achievementsScreen'));window.scrollTo(0,0);labels();load()}
function close(){request++;loading=false;document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('active',e.id==='home'));window.scrollTo(0,0)}
$('achievementsEntry').onclick=open;$('profileAchievements').onclick=open;$('achievementsBack').onclick=close;$('achievementsHome').onclick=close;$('achievementsRetry').onclick=load;
window.addEventListener('storage',e=>{if(e.key==='pw.language'){labels();if(active())load()}});document.addEventListener('visibilitychange',()=>{if(active()&&!document.hidden&&!claiming.size)load()});
window.PWAchievements={open,labels,api};labels();async function preload(){if(active()||claiming.size)return;const l=language(),token=request;try{await pw.login();const j=await api('state');if(l===language()&&token===request&&!active())apply(j)}catch{}}$('profileBtn').addEventListener('click',preload);preload();
})();
