(() => {
'use strict';
const $=id=>document.getElementById(id),pw=window.PW;
const lang=()=>{try{return localStorage.getItem('pw.language')||'ru'}catch{return'ru'}};
const names={ru:['Бронза','Серебро','Золото','Алмаз','Знаток','Дуэлянт','Чемпион','Огненная серия','Космос','Коллекционер'],en:['Bronze','Silver','Gold','Diamond','Scholar','Duelist','Champion','Flame streak','Cosmos','Collector'],az:['Bürünc','Gümüş','Qızıl','Almaz','Bilici','Duelçi','Çempion','Alov seriyası','Kosmos','Kolleksiyaçı']};
const ids=['bronze','silver','gold','diamond','scholar','duelist','champion','flame','cosmos','collector'];
const symbols=['✦','✧','✦','◆','❖','⚔','♛','♨','✧','❋'];
const copy={
ru:{title:'Оформление',subtitle:'Твои победы — твой стиль',collection:'Коллекция рамок',preview:'ПРИМЕРКА',none:'Без рамки',base:'Классический профиль',baseDesc:'Можно вернуться к оформлению без рамки в любой момент.',open:'Открыта',locked:'Пока закрыта',equipped:'Установлена',equip:'УСТАНОВИТЬ РАМКУ',remove:'УБРАТЬ РАМКУ',need:'ВЫПОЛНИ УСЛОВИЕ',loading:'Загружаю коллекцию…',saving:'Сохраняю…',saved:'Рамка сохранена',error:'Не удалось подтвердить выбор. Попробуй ещё раз.',retry:'ПОВТОРИТЬ',note:'Рамки открываются за достижения. Выбирай любую открытую — менять можно бесплатно. Коллекция сохраняется при сбросе прогресса.',count:n=>n+' / 10',back:'Назад'},
en:{title:'Appearance',subtitle:'Your victories. Your style.',collection:'Frame collection',preview:'PREVIEW',none:'No frame',base:'Classic profile',baseDesc:'You can return to a profile without a frame at any time.',open:'Unlocked',locked:'Locked',equipped:'Equipped',equip:'EQUIP FRAME',remove:'REMOVE FRAME',need:'COMPLETE THE GOAL',loading:'Loading collection…',saving:'Saving…',saved:'Frame saved',error:'Could not confirm your choice. Try again.',retry:'RETRY',note:'Achievements unlock frames. Switch between unlocked frames for free. Your collection survives a progress reset.',count:n=>n+' / 10',back:'Back'},
az:{title:'Görünüş',subtitle:'Qələbələrin — sənin üslubun',collection:'Çərçivə kolleksiyası',preview:'ÖNİZLƏMƏ',none:'Çərçivəsiz',base:'Klassik profil',baseDesc:'İstənilən vaxt çərçivəsiz profilə qayıda bilərsən.',open:'Açılıb',locked:'Bağlıdır',equipped:'Seçilib',equip:'ÇƏRÇİVƏNİ SEÇ',remove:'ÇƏRÇİVƏNİ SİL',need:'ŞƏRTİ TAMAMLA',loading:'Kolleksiya yüklənir…',saving:'Saxlanılır…',saved:'Çərçivə saxlanıldı',error:'Seçimini təsdiqləmək olmadı. Yenidən cəhd et.',retry:'TƏKRARLA',note:'Nailiyyətlər çərçivələri açır. Açıq çərçivələri pulsuz dəyiş. Kolleksiya tərəqqini sıfırladıqda da qalır.',count:n=>n+' / 10',back:'Geri'}
};
const t=()=>copy[lang()]||copy.ru;
let frames=[],selected=null,preview=null,busy=false,loading=false,request=0;
const active=()=>$('framesScreen').classList.contains('active');
function decorate(el,id){if(!el)return;el.classList.add('frame-avatar');if(ids.includes(id)){el.dataset.frame=id;el.dataset.ornament=symbols[ids.indexOf(id)]}else{delete el.dataset.frame;delete el.dataset.ornament}}
function paintOwn(){for(const id of ['avatar','profileAvatar'])decorate($(id),selected)}
function accept(j){if(!Array.isArray(j.frames))return;frames=j.frames;selected=j.avatar_frame||null;paintOwn();if(active()&&!busy)paint()}
function label(id){return (names[lang()]||names.ru)[ids.indexOf(id)]}
function node(tag,cls,text){const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e}
function initial(){return pw.name(pw.player||{}).charAt(0).toUpperCase()||'P'}
function paint(){const x=t(),f=frames.find(f=>f.id===preview),isSelected=preview===selected,available=preview===null||f?.unlocked;
 $('framesCount').textContent=x.count(frames.filter(f=>f.unlocked).length);$('framePreview').textContent=initial();decorate($('framePreview'),preview);
 $('frameName').textContent=preview?label(preview):x.base;$('frameCondition').textContent=preview?(f?.description||x.loading):x.baseDesc;$('frameState').textContent=loading?x.loading:isSelected?x.equipped:available?x.open:x.locked+(f?` · ${f.progress} / ${f.target}`:'');
 $('framesEquip').textContent=busy?x.saving:isSelected?x.equipped:!available?x.need:preview?x.equip:x.remove;$('framesEquip').disabled=busy||loading||isSelected||!available;$('framesNone').disabled=busy||loading;$('framesNone').setAttribute('aria-pressed',String(preview===null));
 const list=$('framesList');list.replaceChildren();for(const id of ids){const f=frames.find(f=>f.id===id),card=node('button','frame-card'+(id===preview?' chosen':'')+(f?.unlocked?' unlocked':''));card.type='button';card.dataset.frameId=id;card.disabled=busy;card.setAttribute('aria-pressed',String(id===preview));card.setAttribute('aria-label',label(id)+' · '+(f?.unlocked?x.open:x.locked));const avatar=node('span','frame-avatar frame-thumb',initial());decorate(avatar,id);card.append(avatar,node('b','',label(id)),node('small','',id===selected?x.equipped:f?.unlocked?x.open:loading?'…':x.locked));if(f&&!f.unlocked){const progress=node('span','frame-progress');const bar=node('i','');bar.style.width=Math.min(100,100*f.progress/f.target)+'%';progress.append(bar);card.append(progress)}card.onclick=()=>{preview=id;$('framesStatus').textContent='';paint();window.scrollTo({top:0,behavior:'instant'})};list.append(card)}
}
function labels(){const x=t();$('profileFrames').textContent='✧ '+x.title+' ›';$('framesTitle').textContent=x.title;$('framesSubtitle').textContent=x.subtitle;$('framesCollection').textContent=x.collection;$('frameEyebrow').textContent=x.preview;$('framesNone').textContent=x.none;$('framesNote').textContent=x.note;$('framesRetry').textContent=x.retry;$('framesBack').setAttribute('aria-label',x.back);if(active())paint()}
async function load(){const token=++request;loading=true;paint();$('framesStatus').textContent=t().loading;$('framesRetry').hidden=true;try{await pw.login();const j=await window.PWAchievements.api('state');if(token!==request||!active())return;accept(j);preview=selected;$('framesStatus').textContent=''}catch{if(token===request&&active()){$('framesStatus').textContent=t().error;$('framesRetry').hidden=false}}finally{if(token===request){loading=false;paint()}}}
async function equip(){if(busy||loading)return;const f=frames.find(f=>f.id===preview);if(preview!==null&&!f?.unlocked)return;busy=true;paint();const token=request,id=preview;$('framesStatus').textContent=t().saving;try{const j=await window.PWAchievements.api('equip',{frame:id});if(token!==request)return;accept(j);if(pw.player)pw.player.avatar_frame=selected;paintOwn();$('framesStatus').textContent=t().saved;pw.haptic('success')}catch{if(token===request)$('framesStatus').textContent=t().error}finally{busy=false;if(active())paint()}}
function open(){document.querySelectorAll('.modal').forEach(e=>e.hidden=true);document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('active',e.id==='framesScreen'));window.scrollTo(0,0);preview=selected;labels();load()}
function close(){request++;loading=false;document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('active',e.id==='home'));window.scrollTo(0,0)}
async function hydrateRating(rows){try{const codes=rows.map(p=>p.photoword_id);if(!codes.length)return;const frames=await pw.avatarFrames(codes);document.querySelectorAll('[data-player-code]').forEach(e=>decorate(e,frames[e.dataset.playerCode]))}catch{}}
$('profileFrames').onclick=open;$('framesBack').onclick=close;$('framesEquip').onclick=equip;$('framesRetry').onclick=load;$('framesNone').onclick=()=>{preview=null;paint()};
window.addEventListener('pw:player',e=>{selected=e.detail.avatar_frame||null;paintOwn()});document.addEventListener('visibilitychange',()=>{if(active()&&!document.hidden&&!busy)load()});
window.PWFrames={open,labels,accept,decorate,hydrateRating};selected=pw.player?.avatar_frame||null;labels();paintOwn();
})();
