(() => {
'use strict';
const $=id=>document.getElementById(id),pw=window.PW;
const lang=()=>{try{return localStorage.getItem('pw.language')||'ru'}catch{return'ru'}};
const copy={
 ru:{eyebrow:'ТВОЙ ПРОФИЛЬ',title:'Звание',titles:['Новичок','Знаток','Эксперт','Мастер','Легенда'],next:(name,n)=>`До звания «${name}» — ${n} XP`,max:'Высшее звание достигнуто',wins:'Побед в дуэлях',streak:'Серия загадок дня',days:'дней подряд',showcase:'Избранные достижения',edit:'ВЫБРАТЬ',empty:'Выбери значки, которыми гордишься',slot:'Свободное место',details:'Вся статистика',pick:'Твоя тройка достижений',hint:'Выбери до трёх открытых достижений. Они появятся в профиле.',none:'Пока нет открытых достижений. Играй и выполняй цели — здесь появятся первые значки.',save:'СОХРАНИТЬ',cancel:'Отмена',saving:'Сохраняю…',saved:'Достижения сохранены',loading:'Загружаю профиль…',error:'Не удалось загрузить данные. Попробуй ещё раз.',retry:'ПОВТОРИТЬ',network:'Не удалось подтвердить сохранение. Повтори — выбор не продублируется.',limit:'Можно выбрать не больше трёх.',all:'ОТКРЫТЬ ДОСТИЖЕНИЯ',close:'Закрыть',ready:'Открыто'},
 en:{eyebrow:'YOUR PROFILE',title:'Rank',titles:['Novice','Adept','Expert','Master','Legend'],next:(name,n)=>`${n} XP to ${name}`,max:'Highest rank reached',wins:'Duel wins',streak:'Daily puzzle streak',days:'consecutive days',showcase:'Featured achievements',edit:'CHOOSE',empty:'Choose the badges you are proud of',slot:'Available slot',details:'All statistics',pick:'Your three achievements',hint:'Choose up to three unlocked achievements to display in your profile.',none:'No unlocked achievements yet. Play and complete goals to earn your first badges.',save:'SAVE',cancel:'Cancel',saving:'Saving…',saved:'Achievements saved',loading:'Loading profile…',error:'Could not load the data. Try again.',retry:'RETRY',network:'Could not confirm the save. Try again — your selection will not be duplicated.',limit:'Choose up to three achievements.',all:'OPEN ACHIEVEMENTS',close:'Close',ready:'Unlocked'},
 az:{eyebrow:'SƏNİN PROFİLİN',title:'Rütbə',titles:['Yeni başlayan','Bilici','Ekspert','Usta','Əfsanə'],next:(name,n)=>`${name} rütbəsinə ${n} XP qalıb`,max:'Ən yüksək rütbəyə çatdın',wins:'Duel qələbələri',streak:'Günün tapmacası seriyası',days:'ardıcıl gün',showcase:'Seçilmiş nailiyyətlər',edit:'SEÇ',empty:'Fəxr etdiyin nişanları seç',slot:'Boş yer',details:'Bütün statistika',pick:'Sənin üç nailiyyətin',hint:'Profilində göstərmək üçün üçə qədər açıq nailiyyət seç.',none:'Hələ açıq nailiyyət yoxdur. Oyna və məqsədləri tamamla — ilk nişanların burada görünəcək.',save:'SAXLA',cancel:'Ləğv et',saving:'Saxlanılır…',saved:'Nailiyyətlər saxlanıldı',loading:'Profil yüklənir…',error:'Məlumatları yükləmək olmadı. Yenidən cəhd et.',retry:'TƏKRARLA',network:'Saxlamağı təsdiqləmək olmadı. Yenidən cəhd et — seçimin təkrarlanmayacaq.',limit:'Ən çox üç nailiyyət seçə bilərsən.',all:'NAİLİYYƏTLƏRİ AÇ',close:'Bağla',ready:'Açılıb'}
};
const t=()=>copy[lang()]||copy.ru,thresholds=[0,400,1500,2500,4000];
let items=[],featured=[],draft=[],busy=false,loaded=false,request=0,itemLanguage='',daily=null;
function node(tag,cls,text){const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e}
function rank(p=pw.player||{}){const x=t(),xp=Math.max(0,Number(p.xp||0));let i=thresholds.length-1;while(i>0&&xp<thresholds[i])i--;const end=thresholds[i+1],percent=end?100*(xp-thresholds[i])/(end-thresholds[i]):100;
 $('profileLeague').textContent=x.titles[i];$('profileXpProgress').style.width=Math.min(100,percent)+'%';$('profileXpBar').setAttribute('aria-valuenow',String(Math.round(percent)));$('profileXpBar').setAttribute('aria-label',x.title);$('profileXpTotal').textContent=xp+' XP';$('profileNextRank').textContent=end?x.next(x.titles[i+1],end-xp):x.max;
}
function paintShowcase(){const list=$('profileAchievementBadges');list.replaceChildren();for(let i=0;i<3;i++){const a=items.find(a=>a.id===featured[i]&&a.unlocked),card=node('button','profile-badge'+(a?' earned':''));card.type='button';card.dataset.slot=String(i);card.setAttribute('aria-label',a?a.title:t().slot);card.append(node('span','badge-symbol',a?.icon||'+'),node('small','',a?.title||t().slot));card.onclick=openPicker;list.append(card)}$('profileShowcaseHint').textContent=featured.length?'':t().empty}
function accept(j){if(!Array.isArray(j?.items))return;if(Number(j.progress_generation||0)!==Number(pw.player?.progress_generation||0))return;items=j.items;itemLanguage=lang();featured=Array.isArray(j.featured_achievements)?j.featured_achievements.slice(0,3):pw.player?.featured_achievements||[];loaded=true;if(pw.player)pw.player.featured_achievements=featured.slice();paintShowcase()}
function labels(){const x=t();for(const [id,text] of Object.entries({profileEyebrow:x.eyebrow,profileShowcaseTitle:x.showcase,profileFeaturedBtn:x.edit,profileDetailsLabel:x.details,profileWinsLabel:x.wins,profilePuzzleStreakLabel:x.streak,profileStreakUnit:x.days,featuredTitle:x.pick,featuredHint:x.hint,featuredSave:busy?x.saving:x.save,featuredCancel:x.cancel,featuredAll:x.all,profileOverviewRetry:x.retry}))$(id).textContent=text;document.querySelector('#profileModal [data-close]').setAttribute('aria-label',x.close);rank();paintShowcase();if(!$('featuredModal').hidden)paintPicker()}
function paintPicker(){const x=t(),list=$('featuredList'),unlocked=items.filter(a=>a.unlocked);list.replaceChildren();$('featuredCount').textContent=draft.length+' / 3';$('featuredSave').disabled=busy||!loaded;$('featuredCancel').disabled=busy;$('featuredAll').hidden=unlocked.length>0;$('featuredSave').textContent=busy?x.saving:x.save;
 if(!unlocked.length)list.append(node('p','profile-empty',loaded?x.none:x.loading));
 for(const a of unlocked){const selected=draft.includes(a.id),b=node('button','featured-option'+(selected?' selected':''));b.type='button';b.dataset.achievement=a.id;b.setAttribute('aria-pressed',String(selected));b.disabled=busy||!selected&&draft.length>=3;b.append(node('span','featured-icon',a.icon));const text=node('span','featured-copy');text.append(node('b','',a.title),node('small','',a.description));b.append(text,node('span','featured-check',selected?'✓':'+'));b.onclick=()=>{if(busy)return;if(selected)draft=draft.filter(id=>id!==a.id);else if(draft.length<3)draft.push(a.id);else return;paintPicker()};list.append(b)}
}
async function loadShowcase(){const token=request,l=lang();const j=await window.PWAchievements.api('state');if(token===request&&l===lang())accept(j)}
async function openPicker(){if(busy)return;$('profileModal').hidden=true;$('featuredModal').hidden=false;$('featuredStatus').textContent='';if(itemLanguage!==lang()){items=[];loaded=false;}draft=featured.slice();labels();try{await loadShowcase();draft=featured.slice();paintPicker()}catch{$('featuredStatus').textContent=t().error;}}
function closePicker(){if(busy)return;$('featuredModal').hidden=true;$('profileModal').hidden=false;paintShowcase()}
async function save(){if(busy||!loaded)return;busy=true;paintPicker();const token=request,l=lang();try{const j=await window.PWAchievements.api('showcase',{achievements:draft.slice()});if(token!==request||l!==lang())return;accept(j);$('featuredModal').hidden=true;$('profileModal').hidden=false;pw.status(t().saved);pw.haptic('success')}catch{$('featuredStatus').textContent=t().network}finally{busy=false;paintPicker()}}
async function refresh(){const token=++request;daily=null;$('profileWins').textContent='—';$('profilePuzzleStreak').textContent='—';$('profileOverviewStatus').textContent=t().loading;$('profileOverviewRetry').hidden=true;rank();try{await pw.login();}catch{if(token===request){$('profileOverviewStatus').textContent=t().error;$('profileOverviewRetry').hidden=false;}return}
 const results=await Promise.allSettled([loadShowcase(),pw.duelRequest('statistics'),pw.actionRequest('profile_stats')]);if(token!==request)return;const [showcase,duels,stats]=results;if(duels.status==='fulfilled')$('profileWins').textContent=String(duels.value.stats?.wins||0);if(stats.status==='fulfilled'){daily=stats.value.stats?.daily;$('profilePuzzleStreak').textContent=String(daily?.streak||0);}const failed=results.some(x=>x.status==='rejected');$('profileOverviewStatus').textContent=failed?t().error:'';$('profileOverviewRetry').hidden=!failed;rank();paintShowcase();
}
$('featuredModal').addEventListener('click',e=>{if(e.target===$('featuredModal'))closePicker()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('featuredModal').hidden){e.stopImmediatePropagation();closePicker()}});$('profileFeaturedBtn').onclick=openPicker;$('featuredSave').onclick=save;$('featuredCancel').onclick=closePicker;$('featuredClose').onclick=closePicker;$('featuredAll').onclick=()=>{$('featuredModal').hidden=true;window.PWAchievements.open()};$('profileOverviewRetry').onclick=refresh;$('profileBtn').addEventListener('click',refresh);
window.addEventListener('pw:achievements',e=>accept(e.detail));window.addEventListener('pw:player',e=>{rank(e.detail);featured=e.detail.featured_achievements||[];paintShowcase()});window.addEventListener('pw:reset',()=>{request++;items=[];featured=[];draft=[];loaded=false;busy=false;paintShowcase()});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!$('profileModal').hidden&&!busy)refresh()});
window.PWProfile={labels,accept,refresh};labels();
})();
