create or replace function public.achievement_metrics(p_player uuid) returns jsonb language plpgsql set search_path='' as $$
declare m jsonb;themes jsonb;chapters jsonb;daily_best_streak integer;ds jsonb;duels jsonb;challenges jsonb;
begin
 select jsonb_build_object('main',count(*) filter(where mode='main'),'nohint',count(*) filter(where mode='main' and no_hint),'theme_total',count(*) filter(where mode='theme')) into m from public.achievement_levels where player_id=p_player;
 select coalesce(jsonb_object_agg('theme_'||theme_id,n),'{}'::jsonb)||jsonb_build_object('themes_complete',count(*) filter(where n>=100)) into themes from (select theme_id,count(*) n from public.achievement_levels where player_id=p_player and mode='theme' group by theme_id) t;
 select jsonb_object_agg('chapter_'||i,case when n=last_level-first_level+1 then 1 else 0 end) into chapters from (select b.i,b.first_level,b.last_level,count(l.level_id) n from (values(1,1,20),(2,21,50),(3,51,90),(4,91,130),(5,131,180),(6,181,230),(7,231,280),(8,281,330),(9,331,380),(10,381,430),(11,431,480),(12,481,530)) b(i,first_level,last_level) left join public.achievement_levels l on l.player_id=p_player and l.mode='main' and l.level_id between b.first_level and b.last_level group by b.i,b.first_level,b.last_level) c;
 select coalesce(max(n),0) into daily_best_streak from (select count(*) n from (select puzzle_day-(row_number() over(order by puzzle_day))::integer grp from public.daily_puzzle_progress where player_id=p_player and solved) d group by grp) series;
 select jsonb_build_object('daily_total',count(*),'daily_first',count(*) filter(where attempts=1),'daily_streak',daily_best_streak) into ds from public.daily_puzzle_progress where player_id=p_player and solved;
 select jsonb_build_object('duel_played',count(*),'duel_wins',count(*) filter(where winner=p_player),'duel_draws',count(*) filter(where winner is null),'duel_best',coalesce(max(case when creator=p_player then creator_score else opponent_score end),0)) into duels from public.duel_matches where status='finished' and (creator=p_player or opponent=p_player);
 select jsonb_build_object('challenge_runs',count(*) filter(where reward_coins>0),'challenge_streak',coalesce(max(streak),0),'blitz_best',coalesce(max(score) filter(where mode='blitz'),0)) into challenges from public.challenge_runs where player_id=p_player and finished_at is not null;
 return m||themes||chapters||ds||duels||challenges;
end $$;

insert into public.achievement_catalog(id,category,metric,target,reward_coins,icon,title,description,position) values
('main_20','main','main',20,15,'🧩','{"ru": "20 уровней позади", "en": "20 levels completed", "az": "20 səviyyə tamamlandı"}'::jsonb,'{"ru": "Впервые пройди 20 разных основных уровней.", "en": "Complete 20 different main levels for the first time.", "az": "20 fərqli əsas səviyyəni ilk dəfə keç."}'::jsonb,66),
('main_100','main','main',100,35,'🧩','{"ru": "100 уровней позади", "en": "100 levels completed", "az": "100 səviyyə tamamlandı"}'::jsonb,'{"ru": "Впервые пройди 100 разных основных уровней.", "en": "Complete 100 different main levels for the first time.", "az": "100 fərqli əsas səviyyəni ilk dəfə keç."}'::jsonb,67),
('main_250','main','main',250,75,'🧩','{"ru": "250 уровней позади", "en": "250 levels completed", "az": "250 səviyyə tamamlandı"}'::jsonb,'{"ru": "Впервые пройди 250 разных основных уровней.", "en": "Complete 250 different main levels for the first time.", "az": "250 fərqli əsas səviyyəni ilk dəfə keç."}'::jsonb,68),
('main_400','main','main',400,100,'🧩','{"ru": "400 уровней позади", "en": "400 levels completed", "az": "400 səviyyə tamamlandı"}'::jsonb,'{"ru": "Впервые пройди 400 разных основных уровней.", "en": "Complete 400 different main levels for the first time.", "az": "400 fərqli əsas səviyyəni ilk dəfə keç."}'::jsonb,69),
('nohint_100','main','nohint',100,60,'💡','{"ru": "Без помощи · 100", "en": "Without hints · 100", "az": "İpucusuz · 100"}'::jsonb,'{"ru": "Впервые пройди 100 основных уровней без платных подсказок. Перемешивание разрешено.", "en": "First-complete 100 main levels without paid hints. Shuffling is allowed.", "az": "100 əsas səviyyəni ilk dəfə ödənişli ipucusuz keç. Qarışdırmaq olar."}'::jsonb,70),
('nohint_150','main','nohint',150,80,'💡','{"ru": "Без помощи · 150", "en": "Without hints · 150", "az": "İpucusuz · 150"}'::jsonb,'{"ru": "Впервые пройди 150 основных уровней без платных подсказок. Перемешивание разрешено.", "en": "First-complete 150 main levels without paid hints. Shuffling is allowed.", "az": "150 əsas səviyyəni ilk dəfə ödənişli ipucusuz keç. Qarışdırmaq olar."}'::jsonb,71),
('nohint_200','main','nohint',200,100,'💡','{"ru": "Без помощи · 200", "en": "Without hints · 200", "az": "İpucusuz · 200"}'::jsonb,'{"ru": "Впервые пройди 200 основных уровней без платных подсказок. Перемешивание разрешено.", "en": "First-complete 200 main levels without paid hints. Shuffling is allowed.", "az": "200 əsas səviyyəni ilk dəfə ödənişli ipucusuz keç. Qarışdırmaq olar."}'::jsonb,72),
('duel_win_75','duels','duel_wins',75,90,'⚔️','{"ru": "75 побед в дуэлях", "en": "75 duel wins", "az": "75 duel qələbəsi"}'::jsonb,'{"ru": "Выиграй 75 завершённых дуэлей.", "en": "Win 75 settled duels.", "az": "75 tamamlanmış dueldə qalib gəl."}'::jsonb,73),
('duel_win_100','duels','duel_wins',100,100,'⚔️','{"ru": "100 побед в дуэлях", "en": "100 duel wins", "az": "100 duel qələbəsi"}'::jsonb,'{"ru": "Выиграй 100 завершённых дуэлей.", "en": "Win 100 settled duels.", "az": "100 tamamlanmış dueldə qalib gəl."}'::jsonb,74),
('duel_win_200','duels','duel_wins',200,150,'⚔️','{"ru": "200 побед в дуэлях", "en": "200 duel wins", "az": "200 duel qələbəsi"}'::jsonb,'{"ru": "Выиграй 200 завершённых дуэлей.", "en": "Win 200 settled duels.", "az": "200 tamamlanmış dueldə qalib gəl."}'::jsonb,75),
('duel_play_1','duels','duel_played',1,10,'🎮','{"ru": "1 дуэлей", "en": "1 duels", "az": "1 duel"}'::jsonb,'{"ru": "Сыграй 1 дуэлей до завершения.", "en": "Finish 1 duels.", "az": "1 dueli sona çatdır."}'::jsonb,76),
('duel_play_25','duels','duel_played',25,25,'🎮','{"ru": "25 дуэлей", "en": "25 duels", "az": "25 duel"}'::jsonb,'{"ru": "Сыграй 25 дуэлей до завершения.", "en": "Finish 25 duels.", "az": "25 dueli sona çatdır."}'::jsonb,77),
('duel_play_100','duels','duel_played',100,60,'🎮','{"ru": "100 дуэлей", "en": "100 duels", "az": "100 duel"}'::jsonb,'{"ru": "Сыграй 100 дуэлей до завершения.", "en": "Finish 100 duels.", "az": "100 dueli sona çatdır."}'::jsonb,78),
('duel_play_200','duels','duel_played',200,100,'🎮','{"ru": "200 дуэлей", "en": "200 duels", "az": "200 duel"}'::jsonb,'{"ru": "Сыграй 200 дуэлей до завершения.", "en": "Finish 200 duels.", "az": "200 dueli sona çatdır."}'::jsonb,79),
('duel_draw_5','duels','duel_draws',5,15,'🤝','{"ru": "Равные силы · 5", "en": "Evenly matched · 5", "az": "Bərabər güc · 5"}'::jsonb,'{"ru": "Заверши 5 дуэлей вничью. Отменённые комнаты не считаются.", "en": "Finish 5 duels in a draw. Cancelled rooms do not count.", "az": "5 dueli heç-heçə bitir. Ləğv edilən otaqlar sayılmır."}'::jsonb,80),
('duel_draw_10','duels','duel_draws',10,20,'🤝','{"ru": "Равные силы · 10", "en": "Evenly matched · 10", "az": "Bərabər güc · 10"}'::jsonb,'{"ru": "Заверши 10 дуэлей вничью. Отменённые комнаты не считаются.", "en": "Finish 10 duels in a draw. Cancelled rooms do not count.", "az": "10 dueli heç-heçə bitir. Ləğv edilən otaqlar sayılmır."}'::jsonb,81),
('duel_draw_25','duels','duel_draws',25,35,'🤝','{"ru": "Равные силы · 25", "en": "Evenly matched · 25", "az": "Bərabər güc · 25"}'::jsonb,'{"ru": "Заверши 25 дуэлей вничью. Отменённые комнаты не считаются.", "en": "Finish 25 duels in a draw. Cancelled rooms do not count.", "az": "25 dueli heç-heçə bitir. Ləğv edilən otaqlar sayılmır."}'::jsonb,82),
('duel_score_15','duels','duel_best',15,45,'🎯','{"ru": "Точный ответ · 15", "en": "Sharp mind · 15", "az": "Dəqiq cavab · 15"}'::jsonb,'{"ru": "Набери 15 очков в одной завершённой дуэли.", "en": "Score 15 points in one settled duel.", "az": "Bir tamamlanmış dueldə 15 xal topla."}'::jsonb,83),
('duel_score_20','duels','duel_best',20,60,'🎯','{"ru": "Точный ответ · 20", "en": "Sharp mind · 20", "az": "Dəqiq cavab · 20"}'::jsonb,'{"ru": "Набери 20 очков в одной завершённой дуэли.", "en": "Score 20 points in one settled duel.", "az": "Bir tamamlanmış dueldə 20 xal topla."}'::jsonb,84),
('daily_total_5','daily','daily_total',5,15,'📅','{"ru": "Загадки дня · 5", "en": "Daily puzzles · 5", "az": "Günün tapmacaları · 5"}'::jsonb,'{"ru": "Реши загадку дня в 5 разных днях.", "en": "Solve the daily puzzle on 5 different days.", "az": "5 fərqli gündə günün tapmacasını həll et."}'::jsonb,85),
('daily_total_10','daily','daily_total',10,20,'📅','{"ru": "Загадки дня · 10", "en": "Daily puzzles · 10", "az": "Günün tapmacaları · 10"}'::jsonb,'{"ru": "Реши загадку дня в 10 разных днях.", "en": "Solve the daily puzzle on 10 different days.", "az": "10 fərqli gündə günün tapmacasını həll et."}'::jsonb,86),
('daily_total_60','daily','daily_total',60,50,'📅','{"ru": "Загадки дня · 60", "en": "Daily puzzles · 60", "az": "Günün tapmacaları · 60"}'::jsonb,'{"ru": "Реши загадку дня в 60 разных днях.", "en": "Solve the daily puzzle on 60 different days.", "az": "60 fərqli gündə günün tapmacasını həll et."}'::jsonb,87),
('daily_total_150','daily','daily_total',150,90,'📅','{"ru": "Загадки дня · 150", "en": "Daily puzzles · 150", "az": "Günün tapmacaları · 150"}'::jsonb,'{"ru": "Реши загадку дня в 150 разных днях.", "en": "Solve the daily puzzle on 150 different days.", "az": "150 fərqli gündə günün tapmacasını həll et."}'::jsonb,88),
('daily_total_200','daily','daily_total',200,110,'📅','{"ru": "Загадки дня · 200", "en": "Daily puzzles · 200", "az": "Günün tapmacaları · 200"}'::jsonb,'{"ru": "Реши загадку дня в 200 разных днях.", "en": "Solve the daily puzzle on 200 different days.", "az": "200 fərqli gündə günün tapmacasını həll et."}'::jsonb,89),
('daily_total_300','daily','daily_total',300,140,'📅','{"ru": "Загадки дня · 300", "en": "Daily puzzles · 300", "az": "Günün tapmacaları · 300"}'::jsonb,'{"ru": "Реши загадку дня в 300 разных днях.", "en": "Solve the daily puzzle on 300 different days.", "az": "300 fərqli gündə günün tapmacasını həll et."}'::jsonb,90),
('daily_total_365','daily','daily_total',365,175,'📅','{"ru": "Загадки дня · 365", "en": "Daily puzzles · 365", "az": "Günün tapmacaları · 365"}'::jsonb,'{"ru": "Реши загадку дня в 365 разных днях.", "en": "Solve the daily puzzle on 365 different days.", "az": "365 fərqli gündə günün tapmacasını həll et."}'::jsonb,91),
('daily_first_25','daily','daily_first',25,40,'✨','{"ru": "С первой попытки · 25", "en": "First try · 25", "az": "İlk cəhddən · 25"}'::jsonb,'{"ru": "В 25 разных днях реши загадку с первой попытки.", "en": "Solve the daily puzzle on the first attempt on 25 different days.", "az": "25 fərqli gündə tapmacanı ilk cəhddən həll et."}'::jsonb,92),
('daily_first_50','daily','daily_first',50,60,'✨','{"ru": "С первой попытки · 50", "en": "First try · 50", "az": "İlk cəhddən · 50"}'::jsonb,'{"ru": "В 50 разных днях реши загадку с первой попытки.", "en": "Solve the daily puzzle on the first attempt on 50 different days.", "az": "50 fərqli gündə tapmacanı ilk cəhddən həll et."}'::jsonb,93),
('daily_first_100','daily','daily_first',100,100,'✨','{"ru": "С первой попытки · 100", "en": "First try · 100", "az": "İlk cəhddən · 100"}'::jsonb,'{"ru": "В 100 разных днях реши загадку с первой попытки.", "en": "Solve the daily puzzle on the first attempt on 100 different days.", "az": "100 fərqli gündə tapmacanı ilk cəhddən həll et."}'::jsonb,94),
('themes_levels_100','themes','theme_total',100,20,'🗂️','{"ru": "Исследователь тем · 100", "en": "Theme explorer · 100", "az": "Mövzu araşdırıcısı · 100"}'::jsonb,'{"ru": "Впервые пройди 100 разных тематических уровней суммарно во всех разделах.", "en": "First-complete 100 different themed levels across all categories.", "az": "Bütün bölmələr üzrə 100 fərqli mövzu səviyyəsini ilk dəfə keç."}'::jsonb,95),
('themes_levels_300','themes','theme_total',300,40,'🗂️','{"ru": "Исследователь тем · 300", "en": "Theme explorer · 300", "az": "Mövzu araşdırıcısı · 300"}'::jsonb,'{"ru": "Впервые пройди 300 разных тематических уровней суммарно во всех разделах.", "en": "First-complete 300 different themed levels across all categories.", "az": "Bütün bölmələr üzrə 300 fərqli mövzu səviyyəsini ilk dəfə keç."}'::jsonb,96),
('themes_levels_600','themes','theme_total',600,70,'🗂️','{"ru": "Исследователь тем · 600", "en": "Theme explorer · 600", "az": "Mövzu araşdırıcısı · 600"}'::jsonb,'{"ru": "Впервые пройди 600 разных тематических уровней суммарно во всех разделах.", "en": "First-complete 600 different themed levels across all categories.", "az": "Bütün bölmələr üzrə 600 fərqli mövzu səviyyəsini ilk dəfə keç."}'::jsonb,97),
('themes_levels_1000','themes','theme_total',1000,120,'🗂️','{"ru": "Исследователь тем · 1000", "en": "Theme explorer · 1000", "az": "Mövzu araşdırıcısı · 1000"}'::jsonb,'{"ru": "Впервые пройди 1000 разных тематических уровней суммарно во всех разделах.", "en": "First-complete 1000 different themed levels across all categories.", "az": "Bütün bölmələr üzrə 1000 fərqli mövzu səviyyəsini ilk dəfə keç."}'::jsonb,98),
('collector_9','themes','themes_complete',9,90,'🏅','{"ru": "Коллекционер · 9", "en": "Collector · 9", "az": "Kolleksiyaçı · 9"}'::jsonb,'{"ru": "Полностью заверши 9 тематических разделов.", "en": "Fully complete 9 themes.", "az": "9 mövzu bölməsini tam bitir."}'::jsonb,99);
