const tg2=window.Telegram?.WebApp;const A='СОБАКА', pool='СОБАКАНТЛДЕР'.split('');let pick=[],locked=false,fixed=new Set();
const $=id=>document.getElementById(id), slots=$('g2Slots'), letters=$('g2Letters');
function toast(m){const e=$('g2Toast');e.textContent=m;e.style.display='block';clearTimeout(window.t2);window.t2=setTimeout(()=>e.style.display='none',1500)}
function renderSlots(){slots.innerHTML='';for(let i=0;i<A.length;i++){const d=document.createElement('div');d.textContent=fixed.has(i)?A[i]:(pick[i]?.l||'');slots.appendChild(d)}}
function renderLetters(){letters.innerHTML='';pool.sort(()=>Math.random()-.5).forEach(l=>{const d=document.createElement('div');d.textContent=l;d.addEventListener('click',()=>tapLetter(d,l));letters.appendChild(d)})}
function currentWord(){let out='';for(let i=0;i<A.length;i++)out+=fixed.has(i)?A[i]:(pick[i]?.l||'');return out}
function tapLetter(el,l){if(locked||el.classList.contains('used'))return;let pos=-1;for(let i=0;i<A.length;i++)if(!fixed.has(i)&&!pick[i]){pos=i;break}if(pos<0)return;el.classList.add('used');pick[pos]={l,el};renderSlots();if(currentWord().length===A.length){locked=true;if(currentWord()===A){toast('✅ Верно!');complete()}else{slots.classList.add('wrong');toast('❌ Неверное слово');setTimeout(()=>{slots.classList.remove('wrong');pick.forEach(x=>x?.el?.classList.remove('used'));pick=[];renderSlots();locked=false},700)}}}
function getTelegramInitData(){if(tg2?.initData)return tg2.initData;const q=new URLSearchParams(location.search);const hs=location.hash.startsWith('#')?location.hash.slice(1):location.hash;const hp=new URLSearchParams(hs);return q.get('tgWebAppData')||hp.get('tgWebAppData')||''}
async function api(action,extra={}){const initData=getTelegramInitData();if(!initData){toast('Не удалось получить данные Telegram');return null}try{const r=await fetch('https://bqoraxewpcnmidvjlpuy.supabase.co/functions/v1/telegram-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData,action,...extra})});const d=await r.json();if(d.error==='insufficient_coins'){toast('Недостаточно монет');return null}if(!r.ok||!d.player){toast('Ошибка сервера');return null}document.querySelectorAll('.coins').forEach(x=>x.textContent=d.player.coins);return d.player}catch(e){toast('Ошибка соединения');return null}}
async function complete(){const p=await api('complete_level',{levelId:1});locked=false;if(p){toast('✅ +20 монет · +100 XP');setTimeout(()=>{document.querySelector('#game').classList.remove('active');document.querySelector('#home').classList.add('active')},1000)}}
$('g2Shuffle').onclick=()=>{const a=[...letters.children];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}a.forEach(x=>letters.appendChild(x));toast('🔀 Перемешано')};
$('g2Letter').onclick=async()=>{const avail=[];for(let i=0;i<A.length;i++)if(!fixed.has(i))avail.push(i);if(!avail.length)return;const p=await api('use_hint',{hintType:'letter',levelId:1});if(!p)return;const pos=avail[Math.floor(Math.random()*avail.length)];fixed.add(pos);if(pick[pos]){pick[pos].el.classList.remove('used');pick[pos]=null}renderSlots();toast('💡 Буква открыта')};
$('g2Remove').onclick=async()=>{const bad=[...letters.children].filter(x=>!x.classList.contains('used')&&!A.includes(x.textContent)&&!x.classList.contains('removed'));if(!bad.length)return;const p=await api('use_hint',{hintType:'remove',levelId:1});if(!p)return;bad.sort(()=>Math.random()-.5).slice(0,3).forEach(x=>x.classList.add('removed'));toast('🪄 Лишние убраны')};
$('g2Text').onclick=async()=>{if($('g2TextValue').dataset.open)return;const p=await api('use_hint',{hintType:'text',levelId:1});if(!p)return;$('g2TextValue').textContent='Домашнее животное, которое часто называют другом человека';$('g2TextValue').dataset.open='1';toast('💬 Подсказка открыта')};
$('g2Back').onclick=()=>{document.querySelector('#game').classList.remove('active');document.querySelector('#home').classList.add('active')};
renderSlots();renderLetters();