CREATE OR REPLACE FUNCTION public.achievement_metrics(p_player uuid)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $function$
declare m jsonb;themes jsonb;chapters jsonb;daily_best_streak integer;ds jsonb;duels jsonb;challenges jsonb;
begin
 select jsonb_build_object('main',count(*) filter(where mode='main'),'nohint',count(*) filter(where mode='main' and no_hint),'theme_total',count(*) filter(where mode='theme')) into m from public.achievement_levels where player_id=p_player;
 select coalesce(jsonb_object_agg('theme_'||theme_id,n),'{}'::jsonb)||jsonb_build_object('themes_complete',count(*) filter(where n>=100)) into themes from (select theme_id,count(*) n from public.achievement_levels where player_id=p_player and mode='theme' group by theme_id) t;
 select jsonb_object_agg('chapter_'||i,case when n=last_level-first_level+1 then 1 else 0 end) into chapters
 from (select b.i,b.first_level,b.last_level,count(l.level_id) n
       from (values(1,1,20),(2,21,50),(3,51,90),(4,91,130),(5,131,180),(6,181,230),(7,231,280),(8,281,330),(9,331,380),(10,381,430),(11,431,480),(12,481,530),(13,531,580),(14,581,630),(15,631,680)) b(i,first_level,last_level)
       left join public.achievement_levels l on l.player_id=p_player and l.mode='main' and l.level_id between b.first_level and b.last_level
       group by b.i,b.first_level,b.last_level) c;
 select coalesce(max(n),0) into daily_best_streak from (select count(*) n from (select puzzle_day-(row_number() over(order by puzzle_day))::integer grp from public.daily_puzzle_progress where player_id=p_player and solved) d group by grp) series;
 select jsonb_build_object('daily_total',count(*),'daily_first',count(*) filter(where attempts=1),'daily_streak',daily_best_streak) into ds from public.daily_puzzle_progress where player_id=p_player and solved;
 select jsonb_build_object('duel_played',count(*),'duel_wins',count(*) filter(where winner=p_player),'duel_draws',count(*) filter(where winner is null),'duel_best',coalesce(max(case when creator=p_player then creator_score else opponent_score end),0)) into duels from public.duel_matches where status='finished' and (creator=p_player or opponent=p_player) and created_at>=(select progress_reset_at from public.players where id=p_player);
 select jsonb_build_object('challenge_runs',count(*) filter(where reward_coins>0),'challenge_streak',coalesce(max(streak),0),'blitz_best',coalesce(max(score) filter(where mode='blitz'),0)) into challenges from public.challenge_runs where player_id=p_player and finished_at is not null;
 return m||themes||chapters||ds||duels||challenges;
end
$function$;

INSERT INTO public.achievement_catalog (id,category,metric,target,reward_coins,icon,title,description,position) VALUES
('main_600','main','main',600,100,'🏁','{"ru":"600 уровней пройдено","en":"600 levels completed","az":"600 səviyyə tamamlandı"}'::jsonb,'{"ru":"Впервые пройди 600 разных основных уровней.","en":"First-complete 600 different main levels.","az":"600 fərqli əsas səviyyəni ilk dəfə keç."}'::jsonb,100),
('main_680','main','main',680,150,'🏆','{"ru":"Путь до конца","en":"The whole journey","az":"Sonadək yol"}'::jsonb,'{"ru":"Пройди все 680 основных уровней.","en":"Complete all 680 main levels.","az":"680 əsas səviyyənin hamısını keç."}'::jsonb,101),
('nohint_300','main','nohint',300,100,'🧠','{"ru":"Без помощи · 300","en":"Without hints · 300","az":"İpucusuz · 300"}'::jsonb,'{"ru":"Впервые пройди 300 основных уровней без платных подсказок. Перемешивание разрешено.","en":"First-complete 300 main levels without paid hints. Shuffling is allowed.","az":"300 əsas səviyyəni ödənişli ipucusuz ilk dəfə keç. Hərfləri qarışdırmaq olar."}'::jsonb,102),
('nohint_500','main','nohint',500,150,'🧠','{"ru":"Без помощи · 500","en":"Without hints · 500","az":"İpucusuz · 500"}'::jsonb,'{"ru":"Впервые пройди 500 основных уровней без платных подсказок. Перемешивание разрешено.","en":"First-complete 500 main levels without paid hints. Shuffling is allowed.","az":"500 əsas səviyyəni ödənişli ipucusuz ilk dəfə keç. Hərfləri qarışdırmaq olar."}'::jsonb,103),
('nohint_680','main','nohint',680,200,'🧠','{"ru":"Мастер без подсказок","en":"No-hint master","az":"İpucusuz usta"}'::jsonb,'{"ru":"Пройди все 680 основных уровней без платных подсказок. Перемешивание разрешено.","en":"Complete all 680 main levels without paid hints. Shuffling is allowed.","az":"680 əsas səviyyənin hamısını ödənişli ipucusuz keç. Hərfləri qarışdırmaq olar."}'::jsonb,104),
('chapter_13','main','chapter_13',1,35,'📚','{"ru":"Глава 13 завершена","en":"Chapter 13 completed","az":"13-cü fəsil tamamlandı"}'::jsonb,'{"ru":"Пройди все уровни главы 13: 531–580.","en":"Complete every level in chapter 13: 531–580.","az":"13-cü fəslin bütün səviyyələrini keç: 531–580."}'::jsonb,105),
('chapter_14','main','chapter_14',1,40,'📚','{"ru":"Глава 14 завершена","en":"Chapter 14 completed","az":"14-cü fəsil tamamlandı"}'::jsonb,'{"ru":"Пройди все уровни главы 14: 581–630.","en":"Complete every level in chapter 14: 581–630.","az":"14-cü fəslin bütün səviyyələrini keç: 581–630."}'::jsonb,106),
('chapter_15','main','chapter_15',1,50,'📚','{"ru":"Глава 15 завершена","en":"Chapter 15 completed","az":"15-ci fəsil tamamlandı"}'::jsonb,'{"ru":"Пройди все уровни главы 15: 631–680.","en":"Complete every level in chapter 15: 631–680.","az":"15-ci fəslin bütün səviyyələrini keç: 631–680."}'::jsonb,107),
('daily_streak_120','daily','daily_streak',120,200,'☀️','{"ru":"120 дней подряд","en":"120 days in a row","az":"120 gün ardıcıl"}'::jsonb,'{"ru":"Решай загадку дня 120 дней подряд. Учитывается лучшая серия.","en":"Solve the daily puzzle 120 consecutive days. Your best streak counts.","az":"Günün tapmacasını 120 gün ardıcıl həll et. Ən yaxşı seriya sayılır."}'::jsonb,108),
('daily_first_150','daily','daily_first',150,100,'✨','{"ru":"С первой попытки · 150","en":"First try · 150","az":"İlk cəhddən · 150"}'::jsonb,'{"ru":"Реши 150 разных загадок дня с первой попытки.","en":"Solve 150 different daily puzzles on the first try.","az":"150 fərqli günün tapmacasını ilk cəhddən həll et."}'::jsonb,109),
('duel_win_300','duels','duel_wins',300,200,'⚔️','{"ru":"300 побед в дуэлях","en":"300 duel wins","az":"300 duel qələbəsi"}'::jsonb,'{"ru":"Выиграй 300 завершённых дуэлей.","en":"Win 300 settled duels.","az":"300 tamamlanmış dueldə qalib gəl."}'::jsonb,110),
('duel_play_300','duels','duel_played',300,100,'🎮','{"ru":"300 дуэлей","en":"300 duels","az":"300 duel"}'::jsonb,'{"ru":"Сыграй 300 дуэлей до завершения.","en":"Finish 300 duels.","az":"300 dueli sona çatdır."}'::jsonb,111),
('duel_play_500','duels','duel_played',500,150,'🎮','{"ru":"500 дуэлей","en":"500 duels","az":"500 duel"}'::jsonb,'{"ru":"Сыграй 500 дуэлей до завершения.","en":"Finish 500 duels.","az":"500 dueli sona çatdır."}'::jsonb,112),
('duel_draw_50','duels','duel_draws',50,80,'🤝','{"ru":"50 ничьих","en":"50 draws","az":"50 heç-heçə"}'::jsonb,'{"ru":"Заверши 50 дуэлей вничью. Отменённые комнаты не считаются.","en":"Finish 50 duels in a draw. Cancelled rooms do not count.","az":"50 dueli heç-heçə bitir. Ləğv edilən otaqlar sayılmır."}'::jsonb,113),
('duel_score_25','duels','duel_best',25,100,'🎯','{"ru":"Точный ответ · 25","en":"Sharp mind · 25","az":"Dəqiq cavab · 25"}'::jsonb,'{"ru":"Набери 25 очков в одной завершённой дуэли.","en":"Score 25 points in one settled duel.","az":"Bir tamamlanmış dueldə 25 xal topla."}'::jsonb,114),
('challenge_runs_100','challenges','challenge_runs',100,100,'🎟️','{"ru":"100 наградных испытаний","en":"100 rewarded challenges","az":"100 mükafatlı sınaq"}'::jsonb,'{"ru":"Заверши 100 испытаний, за которые сервер начислил награду.","en":"Complete 100 challenge runs that receive a server reward.","az":"Server mükafatı verilən 100 sınağı tamamla."}'::jsonb,115),
('challenge_runs_200','challenges','challenge_runs',200,150,'🎟️','{"ru":"200 наградных испытаний","en":"200 rewarded challenges","az":"200 mükafatlı sınaq"}'::jsonb,'{"ru":"Заверши 200 испытаний, за которые сервер начислил награду.","en":"Complete 200 challenge runs that receive a server reward.","az":"Server mükafatı verilən 200 sınağı tamamla."}'::jsonb,116),
('challenge_streak_20','challenges','challenge_streak',20,80,'🔥','{"ru":"Серия · 20","en":"Streak · 20","az":"Seriya · 20"}'::jsonb,'{"ru":"Собери серию из 20 правильных ответов в одном завершённом испытании.","en":"Reach a streak of 20 correct answers in a finished challenge.","az":"Tamamlanmış bir sınaqda 20 düzgün cavab seriyası qur."}'::jsonb,117),
('blitz_30','challenges','blitz_best',30,80,'⚡','{"ru":"Блиц · 30 очков","en":"Blitz · 30 points","az":"Blits · 30 xal"}'::jsonb,'{"ru":"Набери 30 очков за один раунд «Блица».","en":"Score 30 points in one Blitz run.","az":"Bir Blits oyununda 30 xal topla."}'::jsonb,118),
('theme_levels_1200','themes','theme_total',1200,150,'🌍','{"ru":"Все темы пройдены","en":"All themes explored","az":"Bütün mövzular tamamlandı"}'::jsonb,'{"ru":"Пройди все 1200 тематических уровней во всех 12 разделах.","en":"Complete all 1,200 themed levels across all 12 categories.","az":"12 bölmədəki 1 200 mövzu səviyyəsinin hamısını keç."}'::jsonb,119)
ON CONFLICT (id) DO UPDATE SET category=excluded.category,metric=excluded.metric,target=excluded.target,reward_coins=excluded.reward_coins,icon=excluded.icon,title=excluded.title,description=excluded.description,position=excluded.position;