create table public.daily_puzzle_questions (
 id integer primary key check(id between 1 and 365),
 ru text not null,en text not null,az text not null,
 photos jsonb not null check(jsonb_typeof(photos)='array' and jsonb_array_length(photos)=4)
);
create table public.daily_puzzle_progress (
 player_id uuid references public.players(id) on delete cascade,
 puzzle_day date not null,question_id integer not null references public.daily_puzzle_questions(id),
 attempts integer not null default 0 check(attempts between 0 and 3),
 solved boolean not null default false,updated_at timestamptz not null default now(),
 primary key(player_id,puzzle_day)
);
create table public.daily_puzzle_submissions (
 player_id uuid references public.players(id) on delete cascade,request_id uuid not null,
 puzzle_day date not null,correct boolean not null,reward_coins integer not null check(reward_coins in(0,25)),
 created_at timestamptz not null default now(),primary key(player_id,request_id)
);
alter table public.daily_puzzle_questions enable row level security;
alter table public.daily_puzzle_progress enable row level security;
alter table public.daily_puzzle_submissions enable row level security;
revoke all on public.daily_puzzle_questions,public.daily_puzzle_progress,public.daily_puzzle_submissions from public,anon,authenticated;
grant select on public.daily_puzzle_questions to service_role;
grant select,insert,update,delete on public.daily_puzzle_progress,public.daily_puzzle_submissions to service_role;

create function public.daily_puzzle_day(p_at timestamptz) returns date language sql stable set search_path='' as $$select (p_at at time zone 'Europe/Saratov')::date$$;
create function public.daily_puzzle_index(p_day date) returns integer language sql immutable set search_path='' as $$select (((p_day-date '2026-10-02')%365+365)%365)+1$$;

create function public.daily_puzzle_state(p_telegram_id bigint,p_language text)
returns jsonb language plpgsql set search_path='' as $$
declare v_id uuid;v_day date;v_now timestamptz:=clock_timestamp();q public.daily_puzzle_questions;p public.daily_puzzle_progress;word text;
begin
 if p_language is null or p_language not in('ru','en','az') then raise exception 'bad_language';end if;
 select id into v_id from public.players where telegram_id=p_telegram_id;
 if v_id is null then raise exception 'player_not_found';end if;
 v_day:=public.daily_puzzle_day(v_now);
 select * into q from public.daily_puzzle_questions where id=public.daily_puzzle_index(v_day);
 if q.id is null then raise exception 'daily_not_configured';end if;
 select * into p from public.daily_puzzle_progress where player_id=v_id and puzzle_day=v_day;
 word:=case p_language when 'ru' then q.ru when 'en' then q.en else q.az end;
 return jsonb_build_object('day',v_day,'question_id',q.id,'language',p_language,'photos',q.photos,
  'length',char_length(word),'attempts',coalesce(p.attempts,0),'attempts_left',3-coalesce(p.attempts,0),
  'solved',coalesce(p.solved,false),'closed',coalesce(p.solved,false) or coalesce(p.attempts,0)>=3,
  'reward_coins',25,'server_now',v_now,'reset_at',(v_day+1)::timestamp at time zone 'Europe/Saratov');
end $$;

create function public.daily_puzzle_answer(p_telegram_id bigint,p_day date,p_language text,p_answer text,p_request_id uuid)
returns jsonb language plpgsql set search_path='' as $$
declare v public.players;v_day date;q public.daily_puzzle_questions;p public.daily_puzzle_progress;s public.daily_puzzle_submissions;expected text;ok boolean;
begin
 if p_request_id is null or p_day is null or p_language is null or p_language not in('ru','en','az') then raise exception 'bad_request';end if;
 select * into v from public.players where telegram_id=p_telegram_id for update;
 if v.id is null then raise exception 'player_not_found';end if;
 select * into s from public.daily_puzzle_submissions where player_id=v.id and request_id=p_request_id;
 if found then return jsonb_build_object('correct',s.correct,'reward_coins',s.reward_coins,'day',s.puzzle_day,'duplicate',true);end if;
 v_day:=public.daily_puzzle_day(clock_timestamp());
 if p_day<>v_day then raise exception 'daily_changed';end if;
 select * into q from public.daily_puzzle_questions where id=public.daily_puzzle_index(v_day);
 if q.id is null then raise exception 'daily_not_configured';end if;
 expected:=case p_language when 'ru' then q.ru when 'en' then q.en else q.az end;
 if p_answer is null or char_length(p_answer)<>char_length(expected) or char_length(p_answer)>40 then raise exception 'bad_answer';end if;
 insert into public.daily_puzzle_progress(player_id,puzzle_day,question_id) values(v.id,v_day,q.id) on conflict do nothing;
 select * into p from public.daily_puzzle_progress where player_id=v.id and puzzle_day=v_day for update;
 if p.solved or p.attempts>=3 then raise exception 'daily_closed';end if;
 ok:=p_answer=expected;
 update public.daily_puzzle_progress set attempts=attempts+1,solved=ok,updated_at=clock_timestamp() where player_id=v.id and puzzle_day=v_day;
 if ok then
  update public.players set coins=coins+25 where id=v.id;
  insert into public.coin_transactions(player_id,amount,transaction_type,description) values(v.id,25,'daily_puzzle_reward','Daily puzzle '||v_day);
 end if;
 insert into public.daily_puzzle_submissions(player_id,request_id,puzzle_day,correct,reward_coins) values(v.id,p_request_id,v_day,ok,case when ok then 25 else 0 end);
 return jsonb_build_object('correct',ok,'reward_coins',case when ok then 25 else 0 end,'day',v_day,'duplicate',false);
end $$;
revoke all on function public.daily_puzzle_day(timestamptz),public.daily_puzzle_index(date),public.daily_puzzle_state(bigint,text),public.daily_puzzle_answer(bigint,date,text,text,uuid) from public,anon,authenticated;
grant execute on function public.daily_puzzle_day(timestamptz),public.daily_puzzle_index(date),public.daily_puzzle_state(bigint,text),public.daily_puzzle_answer(bigint,date,text,text,uuid) to service_role;

insert into public.daily_puzzle_questions(id,ru,en,az,photos) values
(1,'ОПЕРА','OPERA','OPERA','["🎭", "🎶", "🎤", "🏛️"]'::jsonb),
(2,'МЕДСЕСТРА','NURSE','TİBBBACISI','["🏥", "💉", "🩹", "🩺"]'::jsonb),
(3,'ПАЛАТКА','TENT','ÇADIR','["⛺", "🏕️", "🌲", "🌙"]'::jsonb),
(4,'МИНЕРАЛ','MINERAL','MİNERAL','["💎", "🪨", "⛏️", "🔬"]'::jsonb),
(5,'ИННОВАЦИЯ','INNOVATION','İNNOVASİYA','["💡", "🚀", "⚙️", "✨"]'::jsonb),
(6,'БОЕВИК','ACTION','DÖYÜŞFİLMİ','["💥", "🥊", "🚗", "🎬"]'::jsonb),
(7,'КОТЛЕТА','PATTY','KOTLET','["🥩", "🍳", "🍽️", "🥔"]'::jsonb),
(8,'НАУТИЛУС','NAUTILUS','NAUTİLUS','["🐚", "🌊", "🌀", "🐙"]'::jsonb),
(9,'АВТОЖИР','GYROCOPTER','AVTOJİR','["🛩️", "🌀", "🌬️", "⚙️"]'::jsonb),
(10,'ХАЛАТ','BATHROBE','XALAT','["👘", "🛁", "🧵", "🏠"]'::jsonb),
(11,'МЫС','CAPE','BURUN','["🏝️", "🌊", "➡️", "🪨"]'::jsonb),
(12,'ЗАНАВЕС','CURTAIN','PƏRDƏ','["🎭", "🟥", "↔️", "💡"]'::jsonb),
(13,'СПАСАТЕЛЬ','RESCUER','XİLASEDİCİ','["🛟", "🚨", "⛑️", "🤝"]'::jsonb),
(14,'СНОУБОРД','SNOWBOARD','SNOUBORD','["🏂", "❄️", "🏔️", "🚠"]'::jsonb),
(15,'БЕЛОК','PROTEIN','ZÜLAL','["🥚", "🧬", "🔬", "💪"]'::jsonb),
(16,'МАССИВ','ARRAY','MASSİV','["📚", "🔢", "🧩", "💻"]'::jsonb),
(17,'ОЗВУЧКА','VOICEOVER','SƏSLƏNDİRMƏ','["🎙️", "🗣️", "🎬", "🔊"]'::jsonb),
(18,'ПЕРЕЦ','PEPPER','BİBƏR','["🫑", "🌶️", "🥗", "🌱"]'::jsonb),
(19,'ПИНГВИН','PENGUIN','PİNQVİN','["🐧", "❄️", "🌊", "🐟"]'::jsonb),
(20,'АЭРОСАНИ','AEROSLED','AEROXİZƏK','["🛷", "❄️", "🌀", "💨"]'::jsonb),
(21,'ПЛИНТУС','SKIRTINGBOARD','PLİNTUS','["🧱", "🪵", "🦶", "🏠"]'::jsonb),
(22,'ЭВКАЛИПТ','EUCALYPTUS','EVKALİPT','["🌳", "🐨", "🌿", "🇦🇺"]'::jsonb),
(23,'РЕПЕТИЦИЯ','REHEARSAL','REPETİSİYA','["🎭", "🔁", "📝", "👥"]'::jsonb),
(24,'ЛАБОРАНТ','LABTECHNICIAN','LABORANT','["🔬", "🧪", "🥼", "🧫"]'::jsonb),
(25,'ОКЕАН','OCEAN','OKEAN','["🌊", "🐋", "🚢", "🌍"]'::jsonb),
(26,'ВЕЩЕСТВО','MATTER','MADDƏ','["🧪", "⚛️", "🧊", "💨"]'::jsonb),
(27,'КИБЕРБЕЗОПАСНОСТЬ','CYBERSECURITY','KİBERTƏHLÜKƏSİZLİK','["🛡️", "💻", "🔐", "🌐"]'::jsonb),
(28,'АПЛОДИСМЕНТЫ','APPLAUSE','ALQIŞ','["👏", "👥", "🎬", "🎉"]'::jsonb),
(29,'ПЕЧЕНЬЕ','COOKIE','PEÇENYE','["🍪", "☕", "🍫", "🧈"]'::jsonb),
(30,'СТРАУС','OSTRICH','DƏVƏQUŞU','["🐦", "🥚", "🏃", "🌍"]'::jsonb),
(31,'ЭЛЕКТРОМОБИЛЬ','ELECTRICCAR','ELEKTROMOBİL','["🚗", "⚡", "🔋", "🔌"]'::jsonb),
(32,'СКАТЕРТЬ','TABLECLOTH','SÜFRƏ','["🍽️", "🧵", "🪵", "🏠"]'::jsonb),
(33,'ГРАД','HAIL','DOLU','["🧊", "☁️", "⬇️", "🌧️"]'::jsonb),
(34,'НОТА','NOTE','NOT','["🎵", "📄", "🎼", "🔤"]'::jsonb),
(35,'БАРМЕН','BARTENDER','BARMEN','["🍹", "🥃", "🍸", "🧊"]'::jsonb),
(36,'ХОСТЕЛ','HOSTEL','HOSTEL','["🛏️", "🎒", "👥", "🏠"]'::jsonb),
(37,'ИССЛЕДОВАТЕЛЬ','RESEARCHER','TƏDQİQATÇI','["🧑‍🔬", "🔍", "📋", "🧪"]'::jsonb),
(38,'ЭКРАН','SCREEN','EKRAN','["🖥️", "📱", "👀", "✨"]'::jsonb),
(39,'ПОСТАНОВЩИК','FILMMAKER','QURULUŞÇU','["🎬", "📣", "🎥", "👤"]'::jsonb),
(40,'ПЛОВ','PILAF','PLOV','["🍚", "🥕", "🍖", "🍽️"]'::jsonb),
(41,'БУРУНДУК','CHIPMUNK','BURUNDUK','["🐿️", "🌰", "🟤", "🌲"]'::jsonb),
(42,'КВАДРОЦИКЛ','QUADBIKE','KVADROSİKL','["🏍️", "4️⃣", "🌲", "🪨"]'::jsonb),
(43,'СУНДУК','CHEST','SANDIQ','["📦", "🔒", "🪵", "🏠"]'::jsonb),
(44,'ИВА','WILLOW','SÖYÜD','["🌳", "💧", "🍃", "⬇️"]'::jsonb),
(45,'ОРНАМЕНТ','ORNAMENT','ORNAMENT','["🌿", "🔁", "🎨", "🏺"]'::jsonb),
(46,'МОДЕЛЬЕР','FASHIONDESIGNER','MODELYER','["👗", "✏️", "🧵", "🎨"]'::jsonb),
(47,'ПРИЛЕТ','ARRIVAL','GƏLİŞ','["🛬", "✈️", "🛄", "👋"]'::jsonb),
(48,'УРАВНЕНИЕ','EQUATION','TƏNLİK','["🧮", "=", "✏️", "📐"]'::jsonb),
(49,'АВТОМАТИКА','AUTOMATION','AVTOMATLAŞMA','["⚙️", "🤖", "🔄", "🏭"]'::jsonb),
(50,'НОМИНАЦИЯ','NOMINATION','NOMİNASİYA','["🏆", "📋", "🎬", "👤"]'::jsonb),
(51,'МАЙОНЕЗ','MAYONNAISE','MAYONEZ','["🥚", "🥗", "🥫", "🥄"]'::jsonb),
(52,'БОБЁР','BEAVER','QUNDUZ','["🦫", "🪵", "💧", "🦷"]'::jsonb),
(53,'ЭВАКУАТОР','TOWTRUCK','EVAKUATOR','["🚛", "🚗", "🪝", "🛣️"]'::jsonb),
(54,'ВАЗА','VASE','GÜLDAN','["💐", "🏺", "💧", "🏠"]'::jsonb),
(55,'ЛАВАНДА','LAVENDER','LAVANDA','["🟣", "🌿", "👃", "🐝"]'::jsonb),
(56,'КУБИЗМ','CUBISM','KUBİZM','["🔷", "🔶", "🟥", "🟦"]'::jsonb),
(57,'ПСИХОЛОГ','PSYCHOLOGIST','PSİXOLOQ','["🧠", "💬", "🛋️", "❤️"]'::jsonb),
(58,'КУРОРТ','RESORT','KURORT','["🏨", "🏖️", "🌴", "😎"]'::jsonb),
(59,'УСКОРЕНИЕ','ACCELERATION','SÜRƏTLƏNMƏ','["🏎️", "💨", "📈", "⏱️"]'::jsonb),
(60,'ОБНОВЛЕНИЕ','UPDATE','YENİLƏMƏ','["🔄", "⬆️", "📱", "💻"]'::jsonb),
(61,'КИНОСТУДИЯ','FILMSTUDIO','KİNOSTUDİYA','["🏢", "🎬", "🏭", "🎞️"]'::jsonb),
(62,'ФАСОЛЬ','BEANS','LOBYA','["🫘", "🍲", "🌱", "🥣"]'::jsonb),
(63,'ПАНДА','PANDA','PANDA','["🐼", "🎋", "⚪", "⚫"]'::jsonb),
(64,'ХЭТЧБЕК','HATCHBACK','HETÇBEK','["🚗", "🚪", "⬆️", "🧳"]'::jsonb),
(65,'ПРАЧЕЧНАЯ','LAUNDRYROOM','CAMAŞIRXANA','["🧺", "💧", "👕", "🫧"]'::jsonb),
(66,'ОВРАГ','RAVINE','YARĞAN','["🌧️", "⬇️", "🪨", "🌾"]'::jsonb),
(67,'КОСТЮМ','COSTUME','KOSTYUM','["👗", "🎭", "🧵", "🎬"]'::jsonb),
(68,'ПРОФЕССОР','PROFESSOR','PROFESSOR','["🎓", "🏫", "📚", "🔬"]'::jsonb),
(69,'ЭКСКУРСИЯ','EXCURSION','EKSKURSİYA','["🚌", "🏛️", "👥", "🎧"]'::jsonb),
(70,'МУТАЦИЯ','MUTATION','MUTASİYA','["🧬", "⚡", "🔬", "🔄"]'::jsonb),
(71,'КРИПТОГРАФИЯ','CRYPTOGRAPHY','KRİPTOQRAFİYA','["🔐", "🔣", "📜", "💻"]'::jsonb),
(72,'МОНОЛОГ','MONOLOGUE','MONOLOQ','["🗣️", "👤", "🎬", "🎭"]'::jsonb),
(73,'КОМПОТ','COMPOTE','KOMPOT','["🍎", "🍒", "🫗", "🍶"]'::jsonb),
(74,'ОМАР','LOBSTER','OMAR','["🦞", "🌊", "🪨", "🦀"]'::jsonb),
(75,'СЦЕПЛЕНИЕ','CLUTCH','İLİŞMƏ','["🚗", "🦶", "⚙️", "🔗"]'::jsonb),
(76,'ПОКРЫВАЛО','BEDSPREAD','YATAQÖRTÜYÜ','["🛏️", "🎨", "🧵", "☀️"]'::jsonb),
(77,'ПИОН','PEONY','PİON','["🌸", "🌿", "🩷", "💐"]'::jsonb),
(78,'ВСПЫШКА','FLASH','FLAŞ','["📸", "⚡", "🌙", "✨"]'::jsonb),
(79,'ПЕКАРЬ','BAKER','ÇÖRƏKÇİ','["🍞", "🥖", "🔥", "👨‍🍳"]'::jsonb),
(80,'РАФТИНГ','RAFTING','RAFTİNQ','["🛶", "🌊", "🦺", "🏞️"]'::jsonb),
(81,'ВИД','SPECIES','NÖV','["🐾", "🌱", "🧬", "📚"]'::jsonb),
(82,'САЙТ','WEBSITE','SAYT','["🌐", "🖥️", "🔗", "📄"]'::jsonb),
(83,'АНШЛАГ','SELLOUT','ANŞLAQ','["🎟️", "🚫", "👥", "🎬"]'::jsonb),
(84,'ТЫКВА','PUMPKIN','BALQABAQ','["🎃", "🍲", "🟠", "🌱"]'::jsonb),
(85,'ШАКАЛ','JACKAL','ÇAQQAL','["🐺", "🌵", "🌙", "🦴"]'::jsonb),
(86,'ШИНА','TYRE','ŞİN','["🛞", "⚫", "🛣️", "💨"]'::jsonb),
(87,'ПОРОГ','THRESHOLD','ASTANA','["🚪", "🦶", "🪵", "🏠"]'::jsonb),
(88,'ДУБ','OAK','PALID','["🌳", "🌰", "🍂", "🪵"]'::jsonb),
(89,'ЭМАЛЬ','ENAMEL','MİNA','["🔥", "🎨", "💍", "🏺"]'::jsonb),
(90,'МЕТЕОРОЛОГ','METEOROLOGIST','METEOROLOQ','["🌦️", "🌡️", "☁️", "📡"]'::jsonb),
(91,'ОТКРЫТКА','POSTCARD','AÇIQCA','["💌", "📮", "🏞️", "✍️"]'::jsonb),
(92,'КОЛБА','FLASK','KOLBA','["⚗️", "🧪", "🔥", "💧"]'::jsonb),
(93,'БЭКАП','BACKUP','EHTİYATNÜSXƏ','["💾", "☁️", "🔄", "🛡️"]'::jsonb),
(94,'ПРОЕКТОР','PROJECTOR','PROYEKTOR','["📽️", "💡", "🎞️", "🖼️"]'::jsonb),
(95,'СОУС','SAUCE','SOUS','["🍅", "🥫", "🍝", "🥄"]'::jsonb),
(96,'ЛЕНИВЕЦ','SLOTH','TƏNBƏL','["🌳", "💤", "🐾", "🐌"]'::jsonb),
(97,'АВТОВОЗ','CARTRANSPORTER','AVTODAŞIYICI','["🚛", "🚗", "🚗", "🛣️"]'::jsonb),
(98,'ЧЕРДАК','ATTIC','ÇARDAQ','["🏠", "⬆️", "📦", "🪵"]'::jsonb),
(99,'ПОДСНЕЖНИК','SNOWDROP','NOVRUZGÜLÜ','["🌼", "❄️", "⚪", "🌱"]'::jsonb),
(100,'КОМПОЗИЦИЯ','COMPOSITION','KOMPOZİSİYA','["🖼️", "📐", "🎨", "👀"]'::jsonb),
(101,'ДИСПЕТЧЕР','DISPATCHER','DİSPETÇER','["🎧", "📞", "🗺️", "🚦"]'::jsonb),
(102,'ТРАНСФЕР','TRANSFER','TRANSFER','["🚐", "✈️", "🏨", "📍"]'::jsonb),
(103,'СТАТИСТИКА','STATISTICS','STATİSTİKA','["📊", "📈", "🔢", "🧮"]'::jsonb),
(104,'АККАУНТ','ACCOUNT','AKKAUNT','["👤", "🔐", "📱", "🌐"]'::jsonb),
(105,'ЗАКУЛИСЬЕ','BACKSTAGE','PƏRDƏARXASI','["🎭", "🚪", "🎬", "👀"]'::jsonb),
(106,'ЙОГУРТ','YOGURT','YOQURT','["🥛", "🥣", "🍓", "🥄"]'::jsonb),
(107,'МОРСКАЯСВИНКА','GUINEAPIG','DƏNİZDONUZU','["🐹", "🥬", "🏠", "🥕"]'::jsonb),
(108,'КАТЕР','MOTORBOAT','KATER','["🚤", "🌊", "⚙️", "💨"]'::jsonb),
(109,'САЛФЕТКА','NAPKIN','SALFET','["🍽️", "🖐️", "📄", "🧵"]'::jsonb),
(110,'КЛЁН','MAPLE','AĞCAQAYIN','["🍁", "🌳", "🍂", "🇨🇦"]'::jsonb),
(111,'КАРТИНА','PAINTING','RƏSM','["🖼️", "🎨", "👀", "🖌️"]'::jsonb),
(112,'ЛЕСНИК','FORESTER','MEŞƏÇİ','["🌲", "🦌", "🔥", "🥾"]'::jsonb),
(113,'ЛАГУНА','LAGOON','LAQUN','["🏝️", "🌊", "🐠", "☀️"]'::jsonb),
(114,'АТМОСФЕРА','ATMOSPHERE','ATMOSFER','["🌍", "☁️", "🌬️", "🌌"]'::jsonb),
(115,'РОУТЕР','ROUTER','ROUTER','["📶", "🌐", "💻", "📱"]'::jsonb),
(116,'ДУБЛЬ','TAKE','DUBL','["🎬", "🔁", "📹", "2️⃣"]'::jsonb),
(117,'ГОВЯДИНА','BEEF','MALƏTİ','["🐄", "🥩", "🍳", "🍲"]'::jsonb),
(118,'АИСТ','STORK','LEYLƏK','["🐦", "🪺", "🏠", "🦵"]'::jsonb),
(119,'МОТОРОЛЛЕР','MOTORSCOOTER','MOTOROLLER','["🛵", "👞", "⚙️", "🏙️"]'::jsonb),
(120,'ШВАБРА','MOP','DÖŞƏMƏSİLƏN','["🧹", "💧", "🪣", "🦶"]'::jsonb),
(121,'НАРЦИСС','DAFFODIL','NƏRGİZ','["🌼", "🟡", "🌱", "🎺"]'::jsonb),
(122,'КОНЦЕРТ','CONCERT','KONSERT','["🎤", "🎟️", "🎶", "👥"]'::jsonb),
(123,'СКУЛЬПТОР','SCULPTOR','HEYKƏLTƏRAŞ','["🗿", "🔨", "🪨", "🎨"]'::jsonb),
(124,'ОБМЕН','EXCHANGE','MÜBADİLƏ','["💱", "🔄", "💵", "💶"]'::jsonb),
(125,'ГЕН','GENE','GEN','["🧬", "👨‍👩‍👧", "🔬", "📘"]'::jsonb),
(126,'БАЗОВАЯСТАНЦИЯ','BASESTATION','BAZASTANSİYASI','["📡", "🏙️", "📶", "📱"]'::jsonb),
(127,'ПРИКВЕЛ','PREQUEL','ÖNHEKAYƏ','["⏪", "🎬", "📖", "🕰️"]'::jsonb),
(128,'МЁД','HONEY','BAL','["🍯", "🐝", "🌼", "🍵"]'::jsonb),
(129,'ЛАМА','LLAMA','LAMA','["🦙", "🏔️", "🧶", "🌿"]'::jsonb),
(130,'ФУРА','SEMITRUCK','TIR','["🚛", "📦", "🛣️", "📏"]'::jsonb),
(131,'КОМОД','CHESTOFDRAWERS','KOMOD','["🗄️", "👕", "🏠", "🪵"]'::jsonb),
(132,'ПЛАТО','PLATEAU','YAYLA','["⛰️", "➖", "🌾", "☁️"]'::jsonb),
(133,'ПЕЙЗАЖ','LANDSCAPE','MƏNZƏRƏ','["🏞️", "🌄", "🖼️", "🎨"]'::jsonb),
(134,'РЕЖИССЕР','DIRECTOR','REJİSSOR','["🎬", "🎥", "📣", "🎭"]'::jsonb),
(135,'ДАЙВИНГ','DIVING','DAYVİNQ','["🤿", "🐠", "🌊", "🪸"]'::jsonb),
(136,'МИКРОБ','MICROBE','MİKROB','["🦠", "🔬", "🧫", "👀"]'::jsonb),
(137,'ПРИЛОЖЕНИЕ','APP','TƏTBİQ','["📱", "🧩", "👆", "⚙️"]'::jsonb),
(138,'КИНОКРЕСЛО','CINEMASEAT','KİNOTOXTU','["💺", "🎬", "🪑", "👀"]'::jsonb),
(139,'ПЕЛЬМЕНИ','DUMPLINGS','DÜŞBƏRƏ','["🥟", "🍖", "🥣", "♨️"]'::jsonb),
(140,'ГОРИЛЛА','GORILLA','QORİLLA','["🦍", "🌳", "💪", "🌍"]'::jsonb),
(141,'БЕТОНОМЕШАЛКА','CEMENTMIXER','BETONQARIŞDIRAN','["🚚", "🌀", "🏗️", "🧱"]'::jsonb),
(142,'ОБУВНИЦА','SHOERACK','AYAQQABIRƏFİ','["👟", "🥿", "🚪", "🪵"]'::jsonb),
(143,'ЛОТОС','LOTUS','LOTOS','["🪷", "💧", "🌸", "🌿"]'::jsonb),
(144,'ВИТРАЖ','STAINEDGLASS','VİTRAJ','["🪟", "🌈", "⛪", "🎨"]'::jsonb),
(145,'ДЕТЕКТИВ','DETECTIVE','DETEKTİV','["🕵️", "🔎", "🧩", "📸"]'::jsonb),
(146,'РЕЙС','FLIGHT','REYS','["✈️", "🕒", "🎫", "🛫"]'::jsonb),
(147,'ЖИДКОСТЬ','LIQUID','MAYE','["💧", "🧪", "🥤", "🌊"]'::jsonb),
(148,'ДИСК','DRIVE','DİSK','["💽", "💾", "🖥️", "📁"]'::jsonb),
(149,'ЗАМЕДЛЕНИЕ','SLOWMOTION','YAVAŞHƏRƏKƏT','["🐢", "⏱️", "🎥", "🎬"]'::jsonb),
(150,'КРУАССАН','CROISSANT','KRUASAN','["🥐", "🧈", "☕", "🌅"]'::jsonb),
(151,'БАБОЧКА','BUTTERFLY','KƏPƏNƏK','["🦋", "🌸", "🐛", "🌈"]'::jsonb),
(152,'ПЕШЕХОДНЫЙПЕРЕХОД','CROSSWALK','PİYADAKEÇİDİ','["🚶", "⚪", "⚫", "🚦"]'::jsonb),
(153,'ТОРШЕР','FLOORLAMP','TORŞER','["💡", "🦵", "📖", "🛋️"]'::jsonb),
(154,'ТАЙГА','TAIGA','TAYQA','["🌲", "❄️", "🐻", "🌲"]'::jsonb),
(155,'МРАМОР','MARBLE','MƏRMƏR','["🪨", "⚪", "🏛️", "🗿"]'::jsonb),
(156,'ОФИЦИАНТ','WAITER','OFİSİANT','["🍽️", "📝", "☕", "🍴"]'::jsonb),
(157,'ГИД','GUIDE','BƏLƏDÇİ','["🗣️", "🗺️", "👥", "📍"]'::jsonb),
(158,'ФОТОСИНТЕЗ','PHOTOSYNTHESIS','FOTOSİNTEZ','["🌿", "☀️", "💧", "🌬️"]'::jsonb),
(159,'ЛОГИН','LOGIN','LOQİN','["👤", "⌨️", "🔐", "🌐"]'::jsonb),
(160,'КИНОБИЛЕТ','MOVIETICKET','KİNOBİLET','["🎟️", "🎬", "💺", "📅"]'::jsonb),
(161,'КУКУРУЗА','CORN','QARĞIDALI','["🌽", "🍿", "🌾", "🧈"]'::jsonb),
(162,'СКАТ','STINGRAY','SKAT','["🌊", "🪽", "🐟", "🏖️"]'::jsonb),
(163,'ЛИМУЗИН','LIMOUSINE','LİMUZİN','["🚘", "📏", "🎩", "🥂"]'::jsonb),
(164,'МЫЛО','SOAP','SABUN','["🧼", "🫧", "🖐️", "💧"]'::jsonb),
(165,'СУГРОБ','SNOWDRIFT','QARYIĞINI','["❄️", "🌬️", "⛰️", "🏠"]'::jsonb),
(166,'ЛОГОТИП','LOGO','LOQO','["🔵", "🔺", "🔤", "🏷️"]'::jsonb),
(167,'ТЕСТИРОВЩИК','TESTER','TESTÇİ','["🧪", "💻", "🐞", "✅"]'::jsonb),
(168,'ВЗЛЕТ','TAKEOFF','UÇUŞ','["🛫", "✈️", "☁️", "⬆️"]'::jsonb),
(169,'ОТКРЫТИЕ','DISCOVERY','KƏŞF','["💡", "🔬", "🎉", "📚"]'::jsonb),
(170,'БЛЮТУЗ','BLUETOOTH','BLUTUZ','["🟦", "📱", "🎧", "📶"]'::jsonb),
(171,'ЗЛОДЕЙ','VILLAIN','MƏNFİOBRAZ','["😈", "🎬", "⚔️", "🦸"]'::jsonb),
(172,'УКСУС','VINEGAR','SİRKƏ','["🍶", "🥗", "😖", "🧪"]'::jsonb),
(173,'КРОКОДИЛ','CROCODILE','TİMSAH','["🐊", "💧", "🦷", "🌴"]'::jsonb),
(174,'АВТОЗАПРАВКА','PETROLSTATION','YANACAQDOLDURMA','["⛽", "🚗", "🛢️", "💳"]'::jsonb),
(175,'ДОМОФОН','INTERCOM','DOMOFON','["🏢", "🚪", "🔊", "🖐️"]'::jsonb),
(176,'ЛИСТВЕННИЦА','LARCH','QARAŞAM','["🌲", "🍂", "🟡", "❄️"]'::jsonb),
(177,'РИФМА','RHYME','QAFİYƏ','["🎵", "🔤", "📝", "🔁"]'::jsonb),
(178,'ИЛЛЮСТРАТОР','ILLUSTRATOR','İLLÜSTRATOR','["✏️", "🎨", "📖", "🖥️"]'::jsonb),
(179,'ПЛЯЖ','BEACH','ÇİMƏRLİK','["🏖️", "🌊", "☀️", "⛱️"]'::jsonb),
(180,'ЗЕМЛЕТРЯСЕНИЕ','EARTHQUAKE','ZƏLZƏLƏ','["🌍", "🏚️", "💥", "🪨"]'::jsonb),
(181,'ДОМЕН','DOMAIN','DOMEN','["🌐", "🔤", "🖥️", "🔗"]'::jsonb),
(182,'КОМЕДИЯ','COMEDY','KOMEDİYA','["😂", "🎬", "😄", "🍿"]'::jsonb),
(183,'ПЕРСИК','PEACH','ŞAFTALI','["🍑", "🌳", "☀️", "🧃"]'::jsonb),
(184,'МОРЖ','WALRUS','MORJ','["🦭", "🦷", "❄️", "🌊"]'::jsonb),
(185,'ПЛОТ','RAFT','SAL','["🪵", "🌊", "🪢", "🧍"]'::jsonb),
(186,'ЛЕСТНИЦА','STAIRCASE','PİLLƏKƏN','["🏠", "⬆️", "🦶", "🪵"]'::jsonb),
(187,'КУВШИНКА','WATERLILY','SUZANBAĞI','["🌸", "💧", "🍃", "🐸"]'::jsonb),
(188,'КОЛЛАЖ','COLLAGE','KOLLAJ','["✂️", "📰", "🧩", "🎨"]'::jsonb),
(189,'КОНДИТЕР','PASTRYCHEF','ŞİRNİYYATÇI','["🎂", "🧁", "🍰", "🍫"]'::jsonb),
(190,'КРУИЗ','CRUISE','KRUIZ','["🛳️", "🌊", "🏝️", "🍹"]'::jsonb),
(191,'ЛАБОРАТОРИЯ','LABORATORY','LABORATORİYA','["🧪", "🏢", "🥼", "🧫"]'::jsonb),
(192,'ВИДЕОКАРТА','GRAPHICSCARD','VİDEOKART','["🎮", "🖥️", "⚙️", "🧊"]'::jsonb),
(193,'КИНОМАН','CINEPHILE','KİNOMAN','["😍", "⭐", "🎬", "👏"]'::jsonb),
(194,'ЧЕСНОК','GARLIC','SARIMSAQ','["🧄", "🍲", "👃", "🌱"]'::jsonb),
(195,'ГАЗЕЛЬ','GAZELLE','CEYRAN','["🦌", "🌾", "💨", "🦵"]'::jsonb),
(196,'ПОДВОДНАЯЛОДКА','SUBMARINE','SUALTIQAYIQ','["🌊", "⬇️", "🔭", "⚙️"]'::jsonb),
(197,'МОЧАЛКА','BATHSPONGE','HAMAMSÜNGƏRİ','["🧽", "🛁", "🫧", "🧼"]'::jsonb),
(198,'ХРИЗАНТЕМА','CHRYSANTHEMUM','XRİZANTEMA','["🌼", "🍂", "🌿", "🌈"]'::jsonb),
(199,'СЮРРЕАЛИЗМ','SURREALISM','SÜRREALİZM','["🌀", "🌙", "🧠", "🎨"]'::jsonb),
(200,'ХИРУРГ','SURGEON','CƏRRAH','["🏥", "🩺", "🔪", "🧤"]'::jsonb),
(201,'СТРАХОВКА','INSURANCE','SIĞORTA','["🛡️", "📄", "✈️", "✅"]'::jsonb),
(202,'ГРАФИК','GRAPH','QRAFİK','["📈", "📊", "📉", "🧮"]'::jsonb),
(203,'МЕТАДАННЫЕ','METADATA','METAMƏLUMAT','["💾", "🏷️", "📊", "🔍"]'::jsonb),
(204,'КИНОКЛУБ','FILMCLUB','KİNOKLUB','["🎬", "👥", "💬", "🏠"]'::jsonb),
(205,'СЛИВКИ','CREAM','QAYMAQ','["🥛", "🍰", "☕", "🐄"]'::jsonb),
(206,'ДИКОБРАЗ','PORCUPINE','OXATANKİRPİ','["🦔", "📏", "🌿", "🦷"]'::jsonb),
(207,'ПОНТОН','PONTOON','PONTON','["🌊", "🛢️", "🪵", "🛟"]'::jsonb),
(208,'ПУФ','OTTOMAN','PUF','["🛋️", "🦶", "🧽", "🏠"]'::jsonb),
(209,'БЕРЁЗА','BIRCH','TOZAĞACI','["🌳", "⚪", "⚫", "🍃"]'::jsonb),
(210,'МИНИАТЮРА','MINIATURE','MİNİATÜR','["🖼️", "🔍", "🎨", "📜"]'::jsonb),
(211,'ЭЛЕКТРИК','ELECTRICIAN','ELEKTRİK','["⚡", "🔌", "💡", "🪛"]'::jsonb),
(212,'СОБОР','CATHEDRAL','KAFEDRAL','["⛪", "🔔", "🏛️", "✨"]'::jsonb),
(213,'МАГМА','MAGMA','MAQMA','["🌋", "🔥", "🪨", "🌍"]'::jsonb),
(214,'БАЗАДАННЫХ','DATABASE','VERİLƏNLƏRBAZASI','["🗄️", "📊", "💾", "🖥️"]'::jsonb),
(215,'РЯД','ROW','CƏRGƏ','["🔢", "💺", "💺", "🎟️"]'::jsonb),
(216,'ПЮРЕ','MASH','PÜRE','["🥔", "🥣", "🧈", "🥄"]'::jsonb),
(217,'КАБАН','BOAR','QABAN','["🐗", "🌲", "🦷", "🌰"]'::jsonb),
(218,'МАГЛЕВ','MAGLEV','MAQLEV','["🚆", "🧲", "💨", "🛤️"]'::jsonb),
(219,'ГАРДЕРОБНАЯ','DRESSINGROOM','QARDEROBOTAĞI','["👗", "👔", "👟", "🚪"]'::jsonb),
(220,'ГЕЙЗЕР','GEYSER','QEYZER','["💧", "♨️", "⬆️", "🪨"]'::jsonb),
(221,'ГРАВЮРА','ENGRAVING','QRAVÜRA','["🪵", "🖋️", "📄", "🖼️"]'::jsonb),
(222,'АСТРОНОМ','ASTRONOMER','ASTRONOM','["🔭", "🌌", "⭐", "🪐"]'::jsonb),
(223,'ТРОПА','TRAIL','CIĞIR','["🥾", "🌲", "🗺️", "⛰️"]'::jsonb),
(224,'ПРЕЛОМЛЕНИЕ','REFRACTION','SINMA','["🌈", "💧", "🔍", "➡️"]'::jsonb),
(225,'ФУНКЦИЯ','FUNCTION','FUNKSİYA','["🔣", "💻", "➡️", "⚙️"]'::jsonb),
(226,'ХРОМАКЕЙ','GREENSCREEN','XRAMAKEY','["🟩", "🎥", "💻", "🌍"]'::jsonb),
(227,'МУКА','FLOUR','UN','["🌾", "🥖", "🍞", "🧑‍🍳"]'::jsonb),
(228,'ФЛАМИНГО','FLAMINGO','FLAMİNQO','["🦩", "🌸", "💧", "🦵"]'::jsonb),
(229,'КРОССОВЕР','CROSSOVER','KROSSOVER','["🚙", "🏙️", "🌲", "🛣️"]'::jsonb),
(230,'ПОЛОТЕНЦЕ','TOWEL','DƏSMAL','["🧺", "💧", "🖐️", "🧵"]'::jsonb),
(231,'ПОРОГИ','RAPIDS','ÇAYASTANALARI','["💧", "🪨", "🌊", "🛶"]'::jsonb),
(232,'РОМАН','NOVEL','ROMAN','["📚", "📖", "🧑‍💻", "☕"]'::jsonb),
(233,'САДОВНИК','GARDENER','BAĞBAN','["🌱", "🌳", "🪴", "💧"]'::jsonb),
(234,'ДОЛИНА','VALLEY','VADİ','["🏞️", "⛰️", "🌿", "🌊"]'::jsonb),
(235,'ЧАСТИЦА','PARTICLE','ZƏRRƏCİK','["⚛️", "🔵", "💨", "🧲"]'::jsonb),
(236,'НЕЙРОСЕТЬ','NEURALNET','NEYRONŞƏBƏKƏ','["🧠", "🔗", "💻", "✨"]'::jsonb),
(237,'КИНОПРОКАТ','DISTRIBUTION','KİNOPROKAT','["🎬", "🚚", "🎟️", "🌍"]'::jsonb),
(238,'ИНДЕЙКА','TURKEY','HİNDQUŞU','["🦃", "🍗", "🎉", "🍽️"]'::jsonb),
(239,'КОЛИБРИ','HUMMINGBIRD','KOLİBRİ','["🐦", "🌺", "🍯", "🪽"]'::jsonb),
(240,'ПАТРУЛЬНАЯМАШИНА','POLICECAR','POLİSMAŞINI','["🚓", "👮", "🚨", "🛣️"]'::jsonb),
(241,'ПРОСТЫНЯ','BEDSHEET','DÖŞƏKAĞI','["🛏️", "⚪", "🧺", "💤"]'::jsonb),
(242,'СИРЕНЬ','LILAC','YASƏMƏN','["🟣", "🌸", "🌳", "👃"]'::jsonb),
(243,'ФАРФОР','PORCELAIN','FARFOR','["🍽️", "⚪", "🏺", "✨"]'::jsonb),
(244,'ПЛОТНИК','CARPENTER','DÜLGƏR','["🪚", "🪵", "🔨", "📐"]'::jsonb),
(245,'ВЕРШИНА','SUMMIT','ZİRVƏ','["🏔️", "🚩", "🥾", "☁️"]'::jsonb),
(246,'СИЛА','FORCE','QÜVVƏ','["💪", "➡️", "⚙️", "📐"]'::jsonb),
(247,'УСТАНОВКА','INSTALL','QURAŞDIRMA','["⬇️", "📦", "💻", "✅"]'::jsonb),
(248,'ПРОСЛУШИВАНИЕ','CALLBACK','TƏKRARSINAQ','["🎭", "👥", "🎬", "✅"]'::jsonb),
(249,'ВАРКА','BOILING','QAYNATMA','["💧", "♨️", "🍲", "⏱️"]'::jsonb),
(250,'КАРАКАТИЦА','CUTTLEFISH','MÜRƏKKƏBBALIĞI','["🦑", "🌊", "🎨", "🖋️"]'::jsonb),
(251,'ФУРГОН','VAN','FURQON','["🚐", "📦", "🚪", "🏙️"]'::jsonb),
(252,'КАРНИЗ','CURTAINROD','KARNİZ','["🪟", "🧵", "🪵", "🏠"]'::jsonb),
(253,'МОХ','MOSS','MAMIR','["🌿", "🪨", "💧", "🌲"]'::jsonb),
(254,'ШРИФТ','FONT','ŞRİFT','["🔤", "🅰️", "✒️", "📄"]'::jsonb),
(255,'ШАХТЕР','MINER','MƏDƏNÇİ','["⛏️", "🪨", "🪖", "⬇️"]'::jsonb),
(256,'НОМЕР','ROOM','OTAQ','["🛏️", "🏨", "🔑", "🚪"]'::jsonb),
(257,'ТКАНЬ','TISSUE','TOXUMA','["🧬", "🔬", "🫀", "🧫"]'::jsonb),
(258,'ПРОГРАММА','PROGRAM','PROQRAM','["💻", "⚙️", "📄", "▶️"]'::jsonb),
(259,'ХЛОПУШКА','CLAPPERBOARD','KLAPET','["🎬", "🎥", "👏", "🔢"]'::jsonb),
(260,'ЛАЗАНЬЯ','LASAGNA','LAZANYA','["🍝", "🧀", "🍅", "🔥"]'::jsonb),
(261,'ЕНОТ','RACCOON','YENOT','["🦝", "🗑️", "🌙", "🐾"]'::jsonb),
(262,'ТРАКТОР','TRACTOR','TRAKTOR','["🚜", "🌾", "⚙️", "🌱"]'::jsonb),
(263,'ПРИЩЕПКА','CLOTHESPEG','PALTARSANCAĞI','["👕", "🪢", "☀️", "🖐️"]'::jsonb),
(264,'БРИЗ','BREEZE','BRİZ','["🌬️", "🌊", "🏖️", "☀️"]'::jsonb),
(265,'АККОРД','CHORD','AKKORD','["🎹", "🎸", "🎼", "🤝"]'::jsonb),
(266,'САНТЕХНИК','PLUMBER','SANTEXNİK','["🚰", "🔧", "🚿", "💧"]'::jsonb),
(267,'ПРОГУЛКА','WALK','GƏZİNTİ','["🚶", "🌳", "📷", "☀️"]'::jsonb),
(268,'ПРОБИРКА','TESTTUBE','SINAQŞÜŞƏSİ','["🧪", "⚗️", "💧", "🥼"]'::jsonb),
(269,'БЛОКЧЕЙН','BLOCKCHAIN','BLOKÇEYN','["⛓️", "🔗", "💻", "🔐"]'::jsonb),
(270,'ЭПИЗОД','EPISODE','EPİZOD','["📺", "1️⃣", "🎬", "⏭️"]'::jsonb),
(271,'ОВСЯНКА','OATMEAL','YULAF','["🥣", "🌾", "🥛", "🌅"]'::jsonb),
(272,'МУРАВЬЕД','ANTEATER','QARIŞQAYEYƏN','["🐜", "👅", "🌿", "🐾"]'::jsonb),
(273,'СПИДОМЕТР','SPEEDOMETER','SPİDOMETR','["🚗", "⏱️", "📏", "💨"]'::jsonb),
(274,'ВАННА','BATHTUB','VANNA','["🛁", "💧", "🫧", "🧼"]'::jsonb),
(275,'ЗАСУХА','DROUGHT','QURAQLIQ','["☀️", "🏜️", "🌱", "🚫"]'::jsonb),
(276,'ОРКЕСТР','ORCHESTRA','ORKESTR','["🎻", "🎺", "🥁", "🎼"]'::jsonb),
(277,'МОРЯК','SAILOR','DƏNİZÇİ','["⚓", "🚢", "🌊", "🪢"]'::jsonb),
(278,'ЛЕДНИК','GLACIER','BUZLAQ','["🧊", "🏔️", "❄️", "💧"]'::jsonb),
(279,'ХРОМОСОМА','CHROMOSOME','XROMOSOM','["🧬", "🔬", "🧪", "📊"]'::jsonb),
(280,'ФАЕРВОЛ','FIREWALL','FAYRVOL','["🧱", "🔥", "🛡️", "🌐"]'::jsonb),
(281,'КИНОЗАЛ','AUDITORIUM','KİNOZAL','["🎟️", "🪑", "📽️", "🍿"]'::jsonb),
(282,'РОЛЛ','ROLL','ROLL','["🍣", "🥢", "🥬", "🍚"]'::jsonb),
(283,'ГЕККОН','GECKO','GEKKON','["🦎", "🧱", "🌙", "🐾"]'::jsonb),
(284,'ДВОРНИКИ','WINDSCREENWIPERS','ŞÜŞƏSİLƏNLƏR','["🚗", "🌧️", "🪟", "🧹"]'::jsonb),
(285,'ЩЁТКА','SCRUBBINGBRUSH','TƏMİZLİKFIRÇASI','["🖐️", "🧹", "🫧", "🧽"]'::jsonb),
(286,'БАРХАН','CRESCENTDUNE','BARXAN','["🏜️", "🌙", "🌬️", "☀️"]'::jsonb),
(287,'РЕЗЕЦ','CHISEL','KƏSKİ','["🔨", "🗿", "🪨", "✋"]'::jsonb),
(288,'ХОРЕОГРАФ','CHOREOGRAPHER','XOREOQRAF','["💃", "📝", "🎵", "👥"]'::jsonb),
(289,'ПОХОД','HIKE','YÜRÜŞ','["🥾", "🎒", "⛰️", "🗺️"]'::jsonb),
(290,'ЭРОЗИЯ','EROSION','EROZİYA','["🌊", "🪨", "💨", "⏳"]'::jsonb),
(291,'РАЗЪЕМ','CONNECTOR','KONNEKTOR','["🔌", "🧩", "💻", "📱"]'::jsonb),
(292,'ЗАВЯЗКА','SETUP','GİRİŞ','["🎬", "1️⃣", "❓", "➡️"]'::jsonb),
(293,'ЗАПЕКАНКА','CASSEROLE','SOBAYEMƏYİ','["🍲", "🧀", "🔥", "🍽️"]'::jsonb),
(294,'ТЮЛЕНЬ','SEAL','SUİTİ','["🦭", "🌊", "🐟", "❄️"]'::jsonb),
(295,'КАНАТКА','CABLECAR','KANATYOLU','["🚠", "🏔️", "🪢", "🏞️"]'::jsonb),
(296,'КОРЗИНА','BASKET','SƏBƏT','["🧺", "🪵", "📦", "🏠"]'::jsonb),
(297,'ЖАСМИН','JASMINE','JASMİN','["⚪", "🌸", "👃", "🌿"]'::jsonb),
(298,'ГРАФИКА','GRAPHICS','QRAFİKA','["✒️", "📐", "⚫", "⚪"]'::jsonb),
(299,'АРХЕОЛОГ','ARCHAEOLOGIST','ARXEOLOQ','["🏺", "⛏️", "🗿", "📜"]'::jsonb),
(300,'ПУТЕШЕСТВИЕ','TRAVEL','SƏYAHƏT','["🌍", "✈️", "🧳", "🗺️"]'::jsonb),
(301,'ОЗОН','OZONE','OZON','["🌍", "☀️", "🛡️", "🌤️"]'::jsonb),
(302,'ОШИБКА','BUG','SƏHV','["🐞", "💻", "⚠️", "🔧"]'::jsonb),
(303,'ДОКУМЕНТАЛКА','DOCUMENTARY','SƏNƏDLİFİLM','["📹", "🌍", "📰", "🎬"]'::jsonb),
(304,'СЛИВА','PLUM','GAVALI','["🟣", "🌳", "🧺", "🍰"]'::jsonb),
(305,'ВЕРБЛЮД','CAMEL','DƏVƏ','["🐪", "🏜️", "💧", "☀️"]'::jsonb),
(306,'БАМПЕР','BUMPER','BAMPER','["🚗", "🛡️", "🛠️", "💥"]'::jsonb),
(307,'КЛАДОВКА','PANTRY','ANBAROTAĞI','["📦", "🫙", "🚪", "🏠"]'::jsonb),
(308,'ВЬЮНОК','BINDWEED','SARMAŞIQOTU','["🌿", "🌀", "⚪", "🌼"]'::jsonb),
(309,'АНИМАЦИЯ','ANIMATION','ANİMASİYA','["🎞️", "🖥️", "🏃", "✨"]'::jsonb),
(310,'ПОРТНОЙ','TAILOR','DƏRZİ','["🧵", "✂️", "👔", "📏"]'::jsonb),
(311,'ПИКНИК','PICNIC','PİKNİK','["🧺", "🥪", "🌳", "☀️"]'::jsonb),
(312,'ЗАРЯД','CHARGE','YÜK','["⚡", "➕", "➖", "🔋"]'::jsonb),
(313,'ШИФРОВАНИЕ','ENCRYPTION','ŞİFRLƏMƏ','["🔐", "🔣", "💻", "🛡️"]'::jsonb),
(314,'СПЕЦЭФФЕКТ','SPECIALEFFECT','XÜSUSİEFFEKT','["💥", "🪄", "🎬", "💻"]'::jsonb),
(315,'ГРЕЧКА','BUCKWHEAT','QARABAŞAQ','["🥣", "🌾", "🍚", "🥄"]'::jsonb),
(316,'МАНГУСТ','MONGOOSE','MANQUST','["🐾", "🐍", "🌿", "⚔️"]'::jsonb),
(317,'РИКША','RICKSHAW','RİKŞA','["🚲", "👥", "🌏", "🛞"]'::jsonb),
(318,'ЖАЛЮЗИ','BLINDS','JALÜZ','["🪟", "☀️", "↕️", "🏠"]'::jsonb),
(319,'РОСА','DEW','ŞEH','["💧", "🌿", "🌅", "☀️"]'::jsonb),
(320,'ФАСАД','FACADE','FASAD','["🏢", "🎨", "🚪", "🪟"]'::jsonb),
(321,'ПЕРЕВОДЧИК','TRANSLATOR','TƏRCÜMƏÇİ','["🌐", "🗣️", "📖", "🔤"]'::jsonb),
(322,'СНЕГОХОД','SNOWMOBILE','QARMAŞINI','["🏔️", "❄️", "🛷", "⚙️"]'::jsonb),
(323,'РАБОТА','WORK','İŞ','["⚙️", "📐", "➡️", "🔋"]'::jsonb),
(324,'ПОДКАСТ','PODCAST','PODKAST','["🎙️", "🎧", "📱", "🔊"]'::jsonb),
(325,'КИНОФЕСТИВАЛЬ','FILMFESTIVAL','KİNOFESTİVAL','["🎬", "🏆", "🌍", "🎟️"]'::jsonb),
(326,'МАНГО','MANGO','MANQO','["🥭", "🌴", "🧃", "🟠"]'::jsonb),
(327,'ГЕПАРД','CHEETAH','HEPARD','["🐆", "💨", "🏃", "🌾"]'::jsonb),
(328,'ПАРКОВКА','PARKING','PARKİNQ','["🅿️", "🚗", "⏱️", "🏙️"]'::jsonb),
(329,'БАЛКОН','BALCONY','BALKON','["🏢", "🌤️", "🪴", "🚪"]'::jsonb),
(330,'ПЛЮЩ','IVY','SARMAŞIQ','["🌿", "🧱", "🏠", "⬆️"]'::jsonb),
(331,'СКУЛЬПТУРА','SCULPTURE','HEYKƏLTƏRAŞLIQ','["🗿", "👐", "🪨", "🎨"]'::jsonb),
(332,'УЧЕНЫЙ','SCIENTIST','ALİM','["🔬", "📚", "🧪", "💡"]'::jsonb),
(333,'БРОНЬ','BOOKING','REZERV','["📱", "🏨", "✅", "📅"]'::jsonb),
(334,'ХЛОРОФИЛЛ','CHLOROPHYLL','XLOROFİL','["🌿", "🟢", "☀️", "🔬"]'::jsonb),
(335,'ВЕБКАМЕРА','WEBCAM','VEBKAMERA','["📹", "💻", "🎥", "🌐"]'::jsonb),
(336,'СПОЙЛЕР','SPOILER','SPOYLER','["🤫", "📖", "🎬", "😮"]'::jsonb),
(337,'ВИШНЯ','CHERRY','GİLAS','["🍒", "🌳", "🧁", "❤️"]'::jsonb),
(338,'ОСЁЛ','DONKEY','UZUNQULAQ','["🫏", "👂", "🧺", "🌾"]'::jsonb),
(339,'РАТРАК','SNOWCAT','RATRAK','["❄️", "🚜", "🏔️", "⚙️"]'::jsonb),
(340,'ТАПОЧКИ','SLIPPERS','BAŞMAQ','["🥿", "🦶", "🏠", "🧶"]'::jsonb),
(341,'ОТЛИВ','LOWTIDE','ÇƏKİLMƏ','["🌊", "🌕", "⬇️", "🏖️"]'::jsonb),
(342,'ГЛИНА','CLAY','GİL','["🏺", "👐", "🟤", "🔥"]'::jsonb),
(343,'ПРОКУРОР','PROSECUTOR','PROKUROR','["⚖️", "🏛️", "📁", "🔍"]'::jsonb),
(344,'ДВОРЕЦ','PALACE','SARAY','["🏛️", "👑", "✨", "📷"]'::jsonb),
(345,'ГАЗ','GAS','QAZ','["💨", "🧪", "☁️", "🎈"]'::jsonb),
(346,'СЕРВЕР','SERVER','SERVER','["🖥️", "🌐", "🗄️", "⚙️"]'::jsonb),
(347,'ПОПКОРН','POPCORN','POPKORN','["🍿", "🌽", "🧈", "🎬"]'::jsonb),
(348,'ГРУША','PEAR','ARMUD','["🍐", "🌳", "🧺", "🍰"]'::jsonb),
(349,'ЁЖ','HEDGEHOG','KİRPİ','["🦔", "🍂", "🌲", "🦀"]'::jsonb),
(350,'МИНИВЭН','MINIVAN','MİNİVEN','["🚐", "👨‍👩‍👧‍👦", "🧳", "🛣️"]'::jsonb),
(351,'ТАБУРЕТ','STOOL','KƏTİL','["🪑", "🪵", "🦵", "🏠"]'::jsonb),
(352,'ПРОЛИВ','STRAIT','BOĞAZ','["🌊", "🏝️", "🏝️", "🚢"]'::jsonb),
(353,'МОЛЬБЕРТ','EASEL','MOLBERT','["🪜", "🖼️", "🎨", "🖌️"]'::jsonb),
(354,'ВОСПИТАТЕЛЬ','EDUCATOR','TƏRBİYƏÇİ','["🧸", "👧", "📚", "🏫"]'::jsonb),
(355,'КЕМПИНГ','CAMPING','KEMPİNQ','["🏕️", "⛺", "🔥", "🌲"]'::jsonb),
(356,'ВЕРОЯТНОСТЬ','PROBABILITY','EHTİMAL','["🎲", "📊", "❓", "🧮"]'::jsonb),
(357,'КОЛОНКА','SPEAKER','DİNAMİK','["🔊", "🎵", "📱", "📶"]'::jsonb),
(358,'ИНТЕРВЬЮ','INTERVIEW','MÜSAHİBƏ','["🎙️", "👥", "❓", "🎬"]'::jsonb),
(359,'СУШИ','SUSHI','SUŞİ','["🍣", "🍚", "🐟", "🥢"]'::jsonb),
(360,'ХОМЯК','HAMSTER','DAĞSİÇANI','["🐹", "🌻", "🛞", "🏠"]'::jsonb),
(361,'МОПЕД','MOPED','MOPED','["🛵", "⚙️", "🛣️", "🪖"]'::jsonb),
(362,'РАСЧЁСКА','COMB','DARAQ','["💇", "🦷", "🖐️", "🪞"]'::jsonb),
(363,'УЩЕЛЬЕ','GORGE','DƏRƏ','["🏔️", "💧", "⬇️", "🪨"]'::jsonb),
(364,'ПАЛИТРА','PALETTE','PALETRA','["🎨", "🌈", "🟣", "🟡"]'::jsonb),
(365,'МАШИНИСТ','TRAINDRIVER','MAŞİNİST','["🚆", "🛤️", "🚦", "👨‍✈️"]'::jsonb);
