begin;

alter table public.theme_level_answers drop constraint theme_level_answers_theme_id_check;
alter table public.theme_level_answers add constraint theme_level_answers_theme_id_check check (theme_id in ('sport','art','professions','travel','science','technology','cinema','food','animals','transport','home','nature'));
alter table public.theme_progress drop constraint theme_progress_theme_id_check;
alter table public.theme_progress add constraint theme_progress_theme_id_check check (theme_id in ('sport','art','professions','travel','science','technology','cinema','food','animals','transport','home','nature'));

CREATE OR REPLACE FUNCTION public.complete_theme_level_server(p_telegram_id bigint, p_theme_id text, p_level_id integer, p_language text, p_answer text, p_reward_coins integer DEFAULT 15, p_reward_xp integer DEFAULT 10)
 RETURNS players
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v public.players;
  v_expected text;
  v_inserted integer;
begin
  if p_theme_id not in ('sport','art','professions','travel','science','technology','cinema','food','animals','transport','home','nature')
     or p_level_id not between 1 and 100
     or p_language not in ('ru','en','az')
     or p_reward_coins is distinct from 15
     or p_reward_xp is distinct from 10 then
    raise exception 'bad_theme_level';
  end if;

  select case p_language when 'ru' then a.ru when 'en' then a.en else a.az end
  into v_expected
  from public.theme_level_answers a
  where a.theme_id=p_theme_id and a.level_id=p_level_id;

  if v_expected is null then raise exception 'bad_theme_level'; end if;
  if trim(coalesce(p_answer,'')) is distinct from v_expected then raise exception 'wrong_answer'; end if;

  select * into v from public.players where telegram_id=p_telegram_id for update;
  if v.id is null then raise exception 'player_not_found'; end if;

  insert into public.theme_progress(player_id,theme_id,level_id)
  values(v.id,p_theme_id,p_level_id)
  on conflict(player_id,theme_id,level_id) do nothing;
  get diagnostics v_inserted = row_count;

  if v_inserted=0 then return v; end if;

  update public.players
  set coins=coins+p_reward_coins,
      xp=xp+p_reward_xp
  where id=v.id
  returning * into v;

  insert into public.coin_transactions(player_id,amount,transaction_type,description)
  values(v.id,p_reward_coins,'theme_level_reward','Theme '||p_theme_id||' level '||p_level_id);

  return v;
end
$function$
;

CREATE OR REPLACE FUNCTION public.spend_theme_hint_server(p_telegram_id bigint, p_theme_id text, p_level_id integer, p_hint_type text, p_cost integer)
 RETURNS players
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v public.players;
  v_expected_cost integer;
begin
  if p_theme_id not in ('sport','art','professions','travel','science','technology','cinema','food','animals','transport','home','nature')
     or p_level_id not between 1 and 100 then
    raise exception 'bad_theme_level';
  end if;
  v_expected_cost := case p_hint_type when 'letter' then 50 when 'remove' then 100 when 'text' then 150 else null end;
  if v_expected_cost is null or p_cost is distinct from v_expected_cost then raise exception 'bad_hint'; end if;

  select * into v from public.players where telegram_id=p_telegram_id for update;
  if v.id is null then raise exception 'player_not_found'; end if;
  if v.coins < p_cost then raise exception 'insufficient_coins'; end if;

  update public.players set coins=coins-p_cost where id=v.id returning * into v;
  insert into public.coin_transactions(player_id,amount,transaction_type,description)
  values(v.id,-p_cost,'theme_hint_'||p_hint_type,'Theme '||p_theme_id||' level '||p_level_id);

  return v;
end
$function$
;

insert into public.theme_level_answers(theme_id,level_id,ru,en,az) values
 ('animals',1,'ЛЕВ','LION','ŞİR'),
 ('animals',2,'ТИГР','TIGER','PƏLƏNG'),
 ('animals',3,'ЛЕОПАРД','LEOPARD','BƏBİR'),
 ('animals',4,'ГЕПАРД','CHEETAH','HEPARD'),
 ('animals',5,'ЯГУАР','JAGUAR','YAQUAR'),
 ('animals',6,'ПУМА','COUGAR','PUMA'),
 ('animals',7,'РЫСЬ','LYNX','VAŞAQ'),
 ('animals',8,'ВОЛК','WOLF','CANAVAR'),
 ('animals',9,'ЛИСА','FOX','TÜLKÜ'),
 ('animals',10,'ШАКАЛ','JACKAL','ÇAQQAL'),
 ('animals',11,'ГИЕНА','HYENA','KAFTAR'),
 ('animals',12,'МЕДВЕДЬ','BEAR','AYI'),
 ('animals',13,'ПАНДА','PANDA','PANDA'),
 ('animals',14,'КОАЛА','KOALA','KOALA'),
 ('animals',15,'КЕНГУРУ','KANGAROO','KENQURU'),
 ('animals',16,'ВОМБАТ','WOMBAT','VOMBAT'),
 ('animals',17,'СЛОН','ELEPHANT','FİL'),
 ('animals',18,'НОСОРОГ','RHINOCEROS','KƏRGƏDAN'),
 ('animals',19,'БЕГЕМОТ','HIPPOPOTAMUS','BEHEMOT'),
 ('animals',20,'ЖИРАФ','GIRAFFE','ZÜRAFƏ'),
 ('animals',21,'ЗЕБРА','ZEBRA','ZEBR'),
 ('animals',22,'АНТИЛОПА','ANTELOPE','ANTİLOP'),
 ('animals',23,'ГАЗЕЛЬ','GAZELLE','CEYRAN'),
 ('animals',24,'ОЛЕНЬ','DEER','MARAL'),
 ('animals',25,'ЛОСЬ','MOOSE','SIĞIN'),
 ('animals',26,'КАБАН','BOAR','QABAN'),
 ('animals',27,'БИЗОН','BISON','BİZON'),
 ('animals',28,'БУЙВОЛ','BUFFALO','CAMIŞ'),
 ('animals',29,'ВЕРБЛЮД','CAMEL','DƏVƏ'),
 ('animals',30,'ЛАМА','LLAMA','LAMA'),
 ('animals',31,'АЛЬПАКА','ALPACA','ALPAKA'),
 ('animals',32,'ОСЁЛ','DONKEY','UZUNQULAQ'),
 ('animals',33,'ЛОШАДЬ','HORSE','AT'),
 ('animals',34,'КОРОВА','COW','İNƏK'),
 ('animals',35,'КОЗА','GOAT','KEÇİ'),
 ('animals',36,'ОВЦА','SHEEP','QOYUN'),
 ('animals',37,'СВИНЬЯ','PIG','DONUZ'),
 ('animals',38,'КРОЛИК','RABBIT','DOVŞAN'),
 ('animals',39,'ХОМЯК','HAMSTER','DAĞSİÇANI'),
 ('animals',40,'МОРСКАЯСВИНКА','GUINEAPIG','DƏNİZDONUZU'),
 ('animals',41,'БЕЛКА','SQUIRREL','DƏLƏ'),
 ('animals',42,'БУРУНДУК','CHIPMUNK','BURUNDUK'),
 ('animals',43,'БОБЁР','BEAVER','QUNDUZ'),
 ('animals',44,'ВЫДРА','OTTER','SUSAMURU'),
 ('animals',45,'БАРСУК','BADGER','PORSUQ'),
 ('animals',46,'ЕНОТ','RACCOON','YENOT'),
 ('animals',47,'СКУНС','SKUNK','SKUNS'),
 ('animals',48,'ЁЖ','HEDGEHOG','KİRPİ'),
 ('animals',49,'ДИКОБРАЗ','PORCUPINE','OXATANKİRPİ'),
 ('animals',50,'КРОТ','MOLE','KÖSTƏBƏK'),
 ('animals',51,'ЛЕТУЧАЯМЫШЬ','BAT','YARASA'),
 ('animals',52,'ЛЕНИВЕЦ','SLOTH','TƏNBƏL'),
 ('animals',53,'МУРАВЬЕД','ANTEATER','QARIŞQAYEYƏN'),
 ('animals',54,'БРОНЕНОСЕЦ','ARMADILLO','ZİREHLİ'),
 ('animals',55,'СУРИКАТ','MEERKAT','SURİKAT'),
 ('animals',56,'МАНГУСТ','MONGOOSE','MANQUST'),
 ('animals',57,'ГОРИЛЛА','GORILLA','QORİLLA'),
 ('animals',58,'ШИМПАНЗЕ','CHIMPANZEE','ŞİMPANZE'),
 ('animals',59,'ОРАНГУТАН','ORANGUTAN','ORANQUTAN'),
 ('animals',60,'ЛЕМУР','LEMUR','LEMUR'),
 ('animals',61,'УТКОНОС','PLATYPUS','ÖRDƏKBURUN'),
 ('animals',62,'ЕХИДНА','ECHIDNA','YEXİDNA'),
 ('animals',63,'ТЮЛЕНЬ','SEAL','SUİTİ'),
 ('animals',64,'МОРЖ','WALRUS','MORJ'),
 ('animals',65,'ДЕЛЬФИН','DOLPHIN','DELFİN'),
 ('animals',66,'КОСАТКА','ORCA','QATİLBALİNA'),
 ('animals',67,'НАРВАЛ','NARWHAL','NARVAL'),
 ('animals',68,'КАШАЛОТ','SPERMWHALE','KAŞALOT'),
 ('animals',69,'АКУЛА','SHARK','AKULA'),
 ('animals',70,'СКАТ','STINGRAY','SKAT'),
 ('animals',71,'ОСЬМИНОГ','OCTOPUS','SƏKKİZAYAQLI'),
 ('animals',72,'КАРАКАТИЦА','CUTTLEFISH','MÜRƏKKƏBBALIĞI'),
 ('animals',73,'МЕДУЗА','JELLYFISH','MEDUZA'),
 ('animals',74,'КРАБ','CRAB','YENGƏC'),
 ('animals',75,'ОМАР','LOBSTER','OMAR'),
 ('animals',76,'НАУТИЛУС','NAUTILUS','NAUTİLUS'),
 ('animals',77,'ЧЕРЕПАХА','TURTLE','TISBAĞA'),
 ('animals',78,'КРОКОДИЛ','CROCODILE','TİMSAH'),
 ('animals',79,'ИГУАНА','IGUANA','İQUANA'),
 ('animals',80,'ХАМЕЛЕОН','CHAMELEON','BUQƏLƏMUN'),
 ('animals',81,'ГЕККОН','GECKO','GEKKON'),
 ('animals',82,'КОБРА','COBRA','KOBRA'),
 ('animals',83,'ПИТОН','PYTHON','PİTON'),
 ('animals',84,'ЛЯГУШКА','FROG','QURBAĞA'),
 ('animals',85,'САЛАМАНДРА','SALAMANDER','SALAMANDRA'),
 ('animals',86,'АКСОЛОТЛЬ','AXOLOTL','AKSOLOTL'),
 ('animals',87,'ПИНГВИН','PENGUIN','PİNQVİN'),
 ('animals',88,'ФЛАМИНГО','FLAMINGO','FLAMİNQO'),
 ('animals',89,'ПЕЛИКАН','PELICAN','QUTAN'),
 ('animals',90,'АИСТ','STORK','LEYLƏK'),
 ('animals',91,'ЖУРАВЛЬ','CRANE','DURNA'),
 ('animals',92,'ЛЕБЕДЬ','SWAN','QUQUŞU'),
 ('animals',93,'ПАВЛИН','PEACOCK','TOVUZQUŞU'),
 ('animals',94,'СТРАУС','OSTRICH','DƏVƏQUŞU'),
 ('animals',95,'КОЛИБРИ','HUMMINGBIRD','KOLİBRİ'),
 ('animals',96,'ДЯТЕЛ','WOODPECKER','AĞACDƏLƏN'),
 ('animals',97,'СОВА','OWL','BAYQUŞ'),
 ('animals',98,'ПОПУГАЙ','PARROT','TUTUQUŞU'),
 ('animals',99,'БАБОЧКА','BUTTERFLY','KƏPƏNƏK'),
 ('animals',100,'СТРЕКОЗА','DRAGONFLY','İYNƏCƏ'),
 ('transport',1,'ДВУХЭТАЖНЫЙАВТОБУС','DOUBLEDECKER','İKİMƏRTƏBƏLİAVTOBUS'),
 ('transport',2,'ТРОЛЛЕЙБУС','TROLLEYBUS','TROLLEYBUS'),
 ('transport',3,'ТРАМВАЙ','TRAM','TRAMVAY'),
 ('transport',4,'МАГЛЕВ','MAGLEV','MAQLEV'),
 ('transport',5,'ЭЛЕКТРИЧКА','COMMUTERTRAIN','ELEKTRİKQATARI'),
 ('transport',6,'ЛОКОМОТИВ','LOCOMOTIVE','LOKOMOTİV'),
 ('transport',7,'ВАГОН','CARRIAGE','VAQON'),
 ('transport',8,'МОНОРЕЛЬС','MONORAIL','MONORELS'),
 ('transport',9,'ЗУБЧАТАЯДОРОГА','RACKRAILWAY','DİŞLİDƏMİRYOLU'),
 ('transport',10,'КАНАТКА','CABLECAR','KANATYOLU'),
 ('transport',11,'МАРШРУТКА','SHAREDTAXI','MARŞRUTTAKSİSİ'),
 ('transport',12,'МИНИВЭН','MINIVAN','MİNİVEN'),
 ('transport',13,'МИКРОАВТОБУС','MINIBUS','MİKROAVTOBUS'),
 ('transport',14,'ПИКАП','PICKUP','PİKAP'),
 ('transport',15,'СЕДАН','SEDAN','SEDAN'),
 ('transport',16,'ХЭТЧБЕК','HATCHBACK','HETÇBEK'),
 ('transport',17,'УНИВЕРСАЛ','STATIONWAGON','UNİVERSAL'),
 ('transport',18,'КАБРИОЛЕТ','CONVERTIBLE','KABRİOLET'),
 ('transport',19,'ЛИМУЗИН','LIMOUSINE','LİMUZİN'),
 ('transport',20,'ВНЕДОРОЖНИК','OFFROADER','YOLSÜZLÜKAVTOMOBİLİ'),
 ('transport',21,'КРОССОВЕР','CROSSOVER','KROSSOVER'),
 ('transport',22,'ЭЛЕКТРОМОБИЛЬ','ELECTRICCAR','ELEKTROMOBİL'),
 ('transport',23,'ГИБРИД','HYBRIDCAR','HİBRİDAVTOMOBİL'),
 ('transport',24,'МОТОЦИКЛ','MOTORCYCLE','MOTOSİKLET'),
 ('transport',25,'МОПЕД','MOPED','MOPED'),
 ('transport',26,'МОТОРОЛЛЕР','MOTORSCOOTER','MOTOROLLER'),
 ('transport',27,'КВАДРОЦИКЛ','QUADBIKE','KVADROSİKL'),
 ('transport',28,'РАТРАК','SNOWCAT','RATRAK'),
 ('transport',29,'БАГГИ','BUGGY','BAQQİ'),
 ('transport',30,'МОНОЦИКЛ','UNICYCLE','MONOSİKL'),
 ('transport',31,'ГИРОСКУТЕР','HOVERBOARD','GİROSKUTER'),
 ('transport',32,'ЭЛЕКТРОСАМОКАТ','ESCOOTER','ELEKTROSAMOKAT'),
 ('transport',33,'РИКША','RICKSHAW','RİKŞA'),
 ('transport',34,'ДИЛИЖАНС','STAGECOACH','DİLİJANS'),
 ('transport',35,'ПОВОЗКА','WAGON','ARABA'),
 ('transport',36,'АЭРОСАНИ','AEROSLED','AEROXİZƏK'),
 ('transport',37,'ТРАКТОР','TRACTOR','TRAKTOR'),
 ('transport',38,'КОМБАЙН','HARVESTER','KOMBAYN'),
 ('transport',39,'ЭКСКАВАТОР','EXCAVATOR','EKSKAVATOR'),
 ('transport',40,'БУЛЬДОЗЕР','BULLDOZER','BULDOZER'),
 ('transport',41,'ПОГРУЗЧИК','FORKLIFT','YÜKLƏYİCİ'),
 ('transport',42,'САМОСВАЛ','DUMPTRUCK','ÖZÜBOŞALDAN'),
 ('transport',43,'БЕТОНОМЕШАЛКА','CEMENTMIXER','BETONQARIŞDIRAN'),
 ('transport',44,'АВТОКРАН','MOBILECRANE','AVTOKRAN'),
 ('transport',45,'ЭВАКУАТОР','TOWTRUCK','EVAKUATOR'),
 ('transport',46,'ФУРА','SEMITRUCK','TIR'),
 ('transport',47,'ГРУЗОВИК','TRUCK','YÜKMAŞINI'),
 ('transport',48,'ФУРГОН','VAN','FURQON'),
 ('transport',49,'ЦИСТЕРНА','TANKERTRUCK','SİSTERNMAŞINI'),
 ('transport',50,'ПОЖАРНАЯМАШИНА','FIREENGINE','YANĞINSÖNDÜRƏNMAŞIN'),
 ('transport',51,'СКОРАЯПОМОЩЬ','AMBULANCE','TƏCİLİYARDIM'),
 ('transport',52,'ПАТРУЛЬНАЯМАШИНА','POLICECAR','POLİSMAŞINI'),
 ('transport',53,'КАТЕР','MOTORBOAT','KATER'),
 ('transport',54,'ПОНТОН','PONTOON','PONTON'),
 ('transport',55,'ПАРОХОД','STEAMSHIP','BUXARGƏMİSİ'),
 ('transport',56,'ЛЕДОКОЛ','ICEBREAKER','BUZQIRAN'),
 ('transport',57,'ТАНКЕР','TANKER','TANKER'),
 ('transport',58,'КОНТЕЙНЕРОВОЗ','CONTAINERSHIP','KONTEYNERGƏMİSİ'),
 ('transport',59,'СУХОГРУЗ','CARGOSHIP','QURUYÜKGƏMİSİ'),
 ('transport',60,'ПОДВОДНАЯЛОДКА','SUBMARINE','SUALTIQAYIQ'),
 ('transport',61,'ПЛОТ','RAFT','SAL'),
 ('transport',62,'КАНОЭ','CANOE','KANOE'),
 ('transport',63,'ГОНОЧНЫЙБОЛИД','RACECAR','YARIŞAVTOMOBİLİ'),
 ('transport',64,'АВТОДОМ','MOTORHOME','AVTOEV'),
 ('transport',65,'АВТОВОЗ','CARTRANSPORTER','AVTODAŞIYICI'),
 ('transport',66,'ПОЛУПРИЦЕП','SEMITRAILER','YARIMQOŞQU'),
 ('transport',67,'ДИРИЖАБЛЬ','AIRSHIP','DİRİJABL'),
 ('transport',68,'АЭРОСТАТ','HOTAIRBALLOON','AEROSTAT'),
 ('transport',69,'ПЛАНЕР','GLIDER','PLANER'),
 ('transport',70,'ГИДРОСАМОЛЁТ','SEAPLANE','HİDROTƏYYARƏ'),
 ('transport',71,'АВИАЛАЙНЕР','AIRLINER','AVİALAYNER'),
 ('transport',72,'ИСТРЕБИТЕЛЬ','FIGHTERJET','QIRICITƏYYARƏ'),
 ('transport',73,'ГРУЗОВОЙСАМОЛЁТ','CARGOPLANE','YÜKTƏYYARƏSİ'),
 ('transport',74,'АВТОЖИР','GYROCOPTER','AVTOJİR'),
 ('transport',75,'АВТОМАГИСТРАЛЬ','MOTORWAY','AVTOMAGİSTRAL'),
 ('transport',76,'ПЕРЕКРЁСТОК','INTERSECTION','YOLAYRICI'),
 ('transport',77,'ЭСТАКАДА','OVERPASS','ESTAKADA'),
 ('transport',78,'СЕРПАНТИН','HAIRPINROAD','SERPANTİN'),
 ('transport',79,'ТРОТУАР','SIDEWALK','SƏKİ'),
 ('transport',80,'ПЕШЕХОДНЫЙПЕРЕХОД','CROSSWALK','PİYADAKEÇİDİ'),
 ('transport',81,'СВЕТОФОР','TRAFFICLIGHT','İŞIQFOR'),
 ('transport',82,'ПАРКОВКА','PARKING','PARKİNQ'),
 ('transport',83,'АВТОЗАПРАВКА','PETROLSTATION','YANACAQDOLDURMA'),
 ('transport',84,'ШЛАГБАУМ','BARRIERGATE','ŞLAQBAUM'),
 ('transport',85,'ШИНА','TYRE','ŞİN'),
 ('transport',86,'РУЛЬ','STEERINGWHEEL','SÜKAN'),
 ('transport',87,'СЦЕПЛЕНИЕ','CLUTCH','İLİŞMƏ'),
 ('transport',88,'ТОРМОЗ','BRAKE','ƏYLƏC'),
 ('transport',89,'АКСЕЛЕРАТОР','ACCELERATOR','AKSELERATOR'),
 ('transport',90,'СПИДОМЕТР','SPEEDOMETER','SPİDOMETR'),
 ('transport',91,'ОДОМЕТР','ODOMETER','ODOMETR'),
 ('transport',92,'БАМПЕР','BUMPER','BAMPER'),
 ('transport',93,'КАПОТ','BONNET','KAPOT'),
 ('transport',94,'БАГАЖНИК','CARBOOT','BAQAJBÖLMƏSİ'),
 ('transport',95,'ФАРА','HEADLIGHT','FARA'),
 ('transport',96,'ПОВОРОТНИК','INDICATOR','DÖNMƏGÖSTƏRİCİSİ'),
 ('transport',97,'ДВОРНИКИ','WINDSCREENWIPERS','ŞÜŞƏSİLƏNLƏR'),
 ('transport',98,'РЕМЕНЬБЕЗОПАСНОСТИ','SEATBELT','TƏHLÜKƏSİZLİKKƏMƏRİ'),
 ('transport',99,'ПОДУШКАБЕЗОПАСНОСТИ','AIRBAG','TƏHLÜKƏSİZLİKYASTIĞI'),
 ('transport',100,'АВТОМОЙКА','CARWASH','AVTOYUMA'),
 ('home',1,'ДИВАН','SOFA','DİVAN'),
 ('home',2,'КРЕСЛО','ARMCHAIR','KRESLO'),
 ('home',3,'ТАБУРЕТ','STOOL','KƏTİL'),
 ('home',4,'СТУЛ','CHAIR','STUL'),
 ('home',5,'СТОЛ','TABLE','MASA'),
 ('home',6,'КОМОД','CHESTOFDRAWERS','KOMOD'),
 ('home',7,'ШКАФ','WARDROBE','ŞKAF'),
 ('home',8,'СЕРВАНТ','SIDEBOARD','SERVANT'),
 ('home',9,'СТЕЛЛАЖ','SHELVINGUNIT','RƏFQURĞUSU'),
 ('home',10,'ПОЛКА','SHELF','RƏF'),
 ('home',11,'ТУМБОЧКА','NIGHTSTAND','TUMBA'),
 ('home',12,'КРОВАТЬ','BED','ÇARPAYI'),
 ('home',13,'МАТРАС','MATTRESS','DÖŞƏK'),
 ('home',14,'ПОДУШКА','PILLOW','YASTIQ'),
 ('home',15,'ОДЕЯЛО','BLANKET','YORĞAN'),
 ('home',16,'ПРОСТЫНЯ','BEDSHEET','DÖŞƏKAĞI'),
 ('home',17,'НАВОЛОЧКА','PILLOWCASE','YASTIQÜZÜ'),
 ('home',18,'ПОКРЫВАЛО','BEDSPREAD','YATAQÖRTÜYÜ'),
 ('home',19,'КОВЁР','CARPET','XALÇA'),
 ('home',20,'ТЮЛЬ','TULLE','TÜL'),
 ('home',21,'ЖАЛЮЗИ','BLINDS','JALÜZ'),
 ('home',22,'КАРНИЗ','CURTAINROD','KARNİZ'),
 ('home',23,'ЛЮСТРА','CHANDELIER','ÇİLÇIRAQ'),
 ('home',24,'ТОРШЕР','FLOORLAMP','TORŞER'),
 ('home',25,'АБАЖУР','LAMPSHADE','ABAJUR'),
 ('home',26,'ПОДСВЕЧНИК','CANDLEHOLDER','ŞAMDAN'),
 ('home',27,'ВАЗА','VASE','GÜLDAN'),
 ('home',28,'КАШПО','PLANTER','GÜLQABI'),
 ('home',29,'ЧАСЫ','CLOCK','SAAT'),
 ('home',30,'БУДИЛЬНИК','ALARMCLOCK','ZƏNGLİSAAT'),
 ('home',31,'ПЛЕД','THROW','YUNÖRTÜK'),
 ('home',32,'ВЕШАЛКА','HANGER','ASILQAN'),
 ('home',33,'КОРЗИНА','BASKET','SƏBƏT'),
 ('home',34,'СУНДУК','CHEST','SANDIQ'),
 ('home',35,'ПУФ','OTTOMAN','PUF'),
 ('home',36,'ПРИХОЖАЯ','HALLWAY','DƏHLİZ'),
 ('home',37,'ГОСТИНАЯ','LIVINGROOM','QONAQOTAĞI'),
 ('home',38,'СПАЛЬНЯ','BEDROOM','YATAQOTAĞI'),
 ('home',39,'КУХНЯ','KITCHEN','MƏTBƏX'),
 ('home',40,'ВАННАЯ','BATHROOM','HAMAMOTAĞI'),
 ('home',41,'КЛАДОВКА','PANTRY','ANBAROTAĞI'),
 ('home',42,'БАЛКОН','BALCONY','BALKON'),
 ('home',43,'ЛОДЖИЯ','LOGGIA','LOJİYA'),
 ('home',44,'ЧЕРДАК','ATTIC','ÇARDAQ'),
 ('home',45,'ПОДВАЛ','CELLAR','ZİRZƏMİ'),
 ('home',46,'ГАРДЕРОБНАЯ','DRESSINGROOM','QARDEROBOTAĞI'),
 ('home',47,'ПРАЧЕЧНАЯ','LAUNDRYROOM','CAMAŞIRXANA'),
 ('home',48,'ЛЕСТНИЦА','STAIRCASE','PİLLƏKƏN'),
 ('home',49,'ПЕРИЛА','BANISTER','MƏHƏCCƏR'),
 ('home',50,'ПОРОГ','THRESHOLD','ASTANA'),
 ('home',51,'ПЛИНТУС','SKIRTINGBOARD','PLİNTUS'),
 ('home',52,'ПАРКЕТ','PARQUET','PARKET'),
 ('home',53,'ЛАМИНАТ','LAMINATE','LAMİNAT'),
 ('home',54,'ОБОИ','WALLPAPER','DİVARKAĞIZI'),
 ('home',55,'ПЛИТКА','TILE','KAFEL'),
 ('home',56,'СМЕСИТЕЛЬ','MIXERTAP','QARIŞDIRICIKRAN'),
 ('home',57,'РАКОВИНА','WASHBASIN','ƏLYUYAN'),
 ('home',58,'УНИТАЗ','TOILET','UNITAZ'),
 ('home',59,'ВАННА','BATHTUB','VANNA'),
 ('home',60,'ДУШ','SHOWER','DUŞ'),
 ('home',61,'ПОЛОТЕНЦЕ','TOWEL','DƏSMAL'),
 ('home',62,'МОЧАЛКА','BATHSPONGE','HAMAMSÜNGƏRİ'),
 ('home',63,'МЫЛО','SOAP','SABUN'),
 ('home',64,'ШАМПУНЬ','SHAMPOO','ŞAMPUN'),
 ('home',65,'ЗУБНАЯЩЁТКА','TOOTHBRUSH','DİŞFIRÇASI'),
 ('home',66,'ЗУБНАЯПАСТА','TOOTHPASTE','DİŞMƏCUNU'),
 ('home',67,'БРИТВА','RAZOR','ÜLGÜC'),
 ('home',68,'РАСЧЁСКА','COMB','DARAQ'),
 ('home',69,'ХАЛАТ','BATHROBE','XALAT'),
 ('home',70,'ТАПОЧКИ','SLIPPERS','BAŞMAQ'),
 ('home',71,'ПИЖАМА','PYJAMAS','PİJAMA'),
 ('home',72,'ФАРТУК','APRON','ÖNLÜK'),
 ('home',73,'ПРИХВАТКА','OVENMITT','SOBAƏLCƏYİ'),
 ('home',74,'ПОДНОС','TRAY','SİNİ'),
 ('home',75,'СКАТЕРТЬ','TABLECLOTH','SÜFRƏ'),
 ('home',76,'САЛФЕТКА','NAPKIN','SALFET'),
 ('home',77,'ГУБКА','SPONGE','SÜNGƏR'),
 ('home',78,'ШВАБРА','MOP','DÖŞƏMƏSİLƏN'),
 ('home',79,'ВЕНИК','BROOM','SÜPÜRGƏ'),
 ('home',80,'СОВОК','DUSTPAN','ZİBİLKÜRƏYİ'),
 ('home',81,'ВЕДРО','BUCKET','VEDRƏ'),
 ('home',82,'ТАЗ','WASHBOWL','LƏYƏN'),
 ('home',83,'ПРИЩЕПКА','CLOTHESPEG','PALTARSANCAĞI'),
 ('home',84,'СУШИЛКА','DRYINGRACK','QURUDUCURƏF'),
 ('home',85,'ГЛАДИЛЬНАЯДОСКА','IRONINGBOARD','ÜTÜMASASI'),
 ('home',86,'МУСОРНОЕВЕДРО','RUBBISHBIN','ZİBİLQABI'),
 ('home',87,'ЩЁТКА','SCRUBBINGBRUSH','TƏMİZLİKFIRÇASI'),
 ('home',88,'ТРЯПКА','CLEANINGCLOTH','ƏSKİ'),
 ('home',89,'МОЮЩЕЕСРЕДСТВО','DETERGENT','YUYUCUVASİTƏ'),
 ('home',90,'УДЛИНИТЕЛЬ','EXTENSIONLEAD','UZADICIKABEL'),
 ('home',91,'ВЫКЛЮЧАТЕЛЬ','LIGHTSWITCH','İŞIQAÇARI'),
 ('home',92,'РОЗЕТКА','SOCKET','ROZETKA'),
 ('home',93,'ДВЕРНОЙЗВОНОК','DOORBELL','QAPIZƏNGİ'),
 ('home',94,'ДВЕРНАЯРУЧКА','DOORHANDLE','QAPIDƏSTƏYİ'),
 ('home',95,'ЩЕКОЛДА','LATCH','CƏFTƏ'),
 ('home',96,'ДОМОФОН','INTERCOM','DOMOFON'),
 ('home',97,'ПОЧТОВЫЙЯЩИК','LETTERBOX','POÇTQUTUSU'),
 ('home',98,'КЛЮЧНИЦА','KEYHOLDER','AÇARLIQ'),
 ('home',99,'ОБУВНИЦА','SHOERACK','AYAQQABIRƏFİ'),
 ('home',100,'ЗОНТОВНИЦА','UMBRELLASTAND','ÇƏTİRDAYAĞI'),
 ('nature',1,'БЕРЁЗА','BIRCH','TOZAĞACI'),
 ('nature',2,'ДУБ','OAK','PALID'),
 ('nature',3,'КЛЁН','MAPLE','AĞCAQAYIN'),
 ('nature',4,'СОСНА','PINE','ŞAM'),
 ('nature',5,'ЕЛЬ','SPRUCE','KÜKNAR'),
 ('nature',6,'ЛИСТВЕННИЦА','LARCH','QARAŞAM'),
 ('nature',7,'КЕДР','CEDAR','SİDR'),
 ('nature',8,'КИПАРИС','CYPRESS','SƏRV'),
 ('nature',9,'ИВА','WILLOW','SÖYÜD'),
 ('nature',10,'ТОПОЛЬ','POPLAR','QOVAQ'),
 ('nature',11,'ОСИНА','ASPEN','AĞCAQOVAQ'),
 ('nature',12,'ЛИПА','LINDEN','CÖKƏ'),
 ('nature',13,'КАШТАН','CHESTNUTTREE','ŞABALIDAĞACI'),
 ('nature',14,'АКАЦИЯ','ACACIA','AKASİYA'),
 ('nature',15,'ЭВКАЛИПТ','EUCALYPTUS','EVKALİPT'),
 ('nature',16,'БАМБУК','BAMBOO','BAMBUK'),
 ('nature',17,'ПАПОРОТНИК','FERN','QIJİ'),
 ('nature',18,'МОХ','MOSS','MAMIR'),
 ('nature',19,'ЛИШАЙНИК','LICHEN','ŞİBYƏ'),
 ('nature',20,'ВОДОРОСЛИ','ALGAE','YOSUN'),
 ('nature',21,'ПЛЮЩ','IVY','SARMAŞIQ'),
 ('nature',22,'КРАПИВА','NETTLE','GİCİTKƏN'),
 ('nature',23,'ОДУВАНЧИК','DANDELION','ZƏNCİROTU'),
 ('nature',24,'РОМАШКА','DAISY','ÇOBANYASTIĞI'),
 ('nature',25,'ВАСИЛЁК','CORNFLOWER','GÜLƏVƏR'),
 ('nature',26,'ПОДСНЕЖНИК','SNOWDROP','NOVRUZGÜLÜ'),
 ('nature',27,'ТЮЛЬПАН','TULIP','LALƏ'),
 ('nature',28,'НАРЦИСС','DAFFODIL','NƏRGİZ'),
 ('nature',29,'РОЗА','ROSE','QIZILGÜL'),
 ('nature',30,'ЛИЛИЯ','LILY','ZANBAQ'),
 ('nature',31,'ОРХИДЕЯ','ORCHID','SƏHLƏB'),
 ('nature',32,'ЛАВАНДА','LAVENDER','LAVANDA'),
 ('nature',33,'СИРЕНЬ','LILAC','YASƏMƏN'),
 ('nature',34,'ЖАСМИН','JASMINE','JASMİN'),
 ('nature',35,'ПИОН','PEONY','PİON'),
 ('nature',36,'ГЕОРГИН','DAHLIA','GEORGİN'),
 ('nature',37,'ХРИЗАНТЕМА','CHRYSANTHEMUM','XRİZANTEMA'),
 ('nature',38,'ИРИС','IRIS','SÜSƏN'),
 ('nature',39,'ГЛАДИОЛУС','GLADIOLUS','QLADİOLUS'),
 ('nature',40,'КОЛОКОЛЬЧИК','BELLFLOWER','ZƏNGÇİÇƏYİ'),
 ('nature',41,'ВЬЮНОК','BINDWEED','SARMAŞIQOTU'),
 ('nature',42,'ПОДОРОЖНИК','PLANTAIN','BAĞAYARPAĞI'),
 ('nature',43,'КЛЕВЕР','CLOVER','YONCA'),
 ('nature',44,'КАМЫШ','BULRUSH','QAMIŞ'),
 ('nature',45,'РОГОЗ','CATTAIL','CİL'),
 ('nature',46,'КУВШИНКА','WATERLILY','SUZANBAĞI'),
 ('nature',47,'ЛОТОС','LOTUS','LOTOS'),
 ('nature',48,'АЛОЭ','ALOE','ALOE'),
 ('nature',49,'АГАВА','AGAVE','AQAVA'),
 ('nature',50,'СУККУЛЕНТ','SUCCULENT','SUKKULENT'),
 ('nature',51,'ДЮНА','DUNE','QUMTƏPƏSİ'),
 ('nature',52,'БАРХАН','CRESCENTDUNE','BARXAN'),
 ('nature',53,'ОАЗИС','OASIS','VAHƏ'),
 ('nature',54,'ПЛАТО','PLATEAU','YAYLA'),
 ('nature',55,'УЩЕЛЬЕ','GORGE','DƏRƏ'),
 ('nature',56,'ОВРАГ','RAVINE','YARĞAN'),
 ('nature',57,'КАРСТ','KARST','KARST'),
 ('nature',58,'СТАЛАКТИТ','STALACTITE','STALAKTİT'),
 ('nature',59,'СТАЛАГМИТ','STALAGMITE','STALAQMİT'),
 ('nature',60,'БОЛОТО','SWAMP','BATAQLIQ'),
 ('nature',61,'ТОРФЯНИК','PEATBOG','TORFLUQ'),
 ('nature',62,'ТУНДРА','TUNDRA','TUNDRA'),
 ('nature',63,'ТАЙГА','TAIGA','TAYQA'),
 ('nature',64,'СТЕПЬ','STEPPE','ÇÖL'),
 ('nature',65,'САВАННА','SAVANNA','SAVANNA'),
 ('nature',66,'МАНГРЫ','MANGROVES','MANQR'),
 ('nature',67,'ОТМЕЛЬ','SHOAL','DAYAZLIQ'),
 ('nature',68,'ЗАВОДЬ','BACKWATER','DURĞUNSU'),
 ('nature',69,'ПРОЛИВ','STRAIT','BOĞAZ'),
 ('nature',70,'ПЕРЕШЕЕК','ISTHMUS','BƏRZƏX'),
 ('nature',71,'АРХИПЕЛАГ','ARCHIPELAGO','ARXİPELAQ'),
 ('nature',72,'МЫС','CAPE','BURUN'),
 ('nature',73,'ФЬОРД','FJORD','FYORD'),
 ('nature',74,'ЭСТУАРИЙ','ESTUARY','ESTUARİ'),
 ('nature',75,'ДЕЛЬТА','RIVERDELTA','ÇAYDELTASI'),
 ('nature',76,'ПРИТОК','TRIBUTARY','ÇAYQOLU'),
 ('nature',77,'РУСЛО','RIVERBED','ÇAYYATAĞI'),
 ('nature',78,'ГЕЙЗЕР','GEYSER','QEYZER'),
 ('nature',79,'ПОРОГИ','RAPIDS','ÇAYASTANALARI'),
 ('nature',80,'МОРЕНА','MORAINE','MOREN'),
 ('nature',81,'АЙСБЕРГ','ICEBERG','AYSBERQ'),
 ('nature',82,'СУГРОБ','SNOWDRIFT','QARYIĞINI'),
 ('nature',83,'ИНЕЙ','FROST','QIROV'),
 ('nature',84,'РОСА','DEW','ŞEH'),
 ('nature',85,'ТУМАН','FOG','DUMAN'),
 ('nature',86,'ГРАД','HAIL','DOLU'),
 ('nature',87,'МЕТЕЛЬ','BLIZZARD','ÇOVĞUN'),
 ('nature',88,'ЛИВЕНЬ','DOWNPOUR','LEYSAN'),
 ('nature',89,'МОРОСЬ','DRIZZLE','ÇİSKİN'),
 ('nature',90,'ЗАСУХА','DROUGHT','QURAQLIQ'),
 ('nature',91,'НАВОДНЕНИЕ','FLOOD','DAŞQIN'),
 ('nature',92,'СМЕРЧ','TORNADO','QASIRĞASÜTUNU'),
 ('nature',93,'УРАГАН','HURRICANE','URAQAN'),
 ('nature',94,'БРИЗ','BREEZE','BRİZ'),
 ('nature',95,'МУССОН','MONSOON','MUSSON'),
 ('nature',96,'ПАССАТ','TRADEWIND','PASSAT'),
 ('nature',97,'ПРИЛИВ','HIGHTIDE','QABARMA'),
 ('nature',98,'ОТЛИВ','LOWTIDE','ÇƏKİLMƏ'),
 ('nature',99,'ПОЛЯРНОЕСИЯНИЕ','AURORA','QÜTBİŞIQLARI'),
 ('nature',100,'ЛИСТОПАД','LEAFFALL','YARPAQTÖKÜLMƏSİ')
on conflict (theme_id,level_id) do update set ru=excluded.ru,en=excluded.en,az=excluded.az;

commit;
