from pathlib import Path
import json
rows=[]
def add(id,cat,metric,target,reward,icon,title,description):
 rows.append(dict(id=id,category=cat,metric=metric,target=target,reward_coins=reward,icon=icon,title=dict(zip(['ru','en','az'],title)),description=dict(zip(['ru','en','az'],description))))
for n,r in [(10,15),(50,25),(150,50),(500,150)]:add(f'main_{n}','main','main',n,r,'🧩',[f'{n} уровней позади',f'{n} levels completed',f'{n} səviyyə tamamlandı'],[f'Впервые пройди {n} разных основных уровней.',f'Complete {n} different main levels for the first time.',f'{n} fərqli əsas səviyyəni ilk dəfə keç.'])
for n,r in [(5,10),(20,20),(40,30),(50,40)]:add(f'nohint_{n}','main','nohint',n,r,'💡',[f'Без помощи · {n}',f'Without hints · {n}',f'İpucusuz · {n}'],[f'Впервые пройди {n} основных уровней без платных подсказок. Перемешивание разрешено.',f'First-complete {n} main levels without paid hints. Shuffling is allowed.',f'{n} əsas səviyyəni ilk dəfə ödənişli ipucusuz keç. Qarışdırmaq olar.'])
for i,end in enumerate([20,50,90,130,180,230,280,330,380,430,480,530],1):add(f'chapter_{i}','main',f'chapter_{i}',1,10 if i<5 else 20,'📚',[f'Глава {i} завершена',f'Chapter {i} completed',f'{i}-ci fəsil tamamlandı'],[f'Пройди все уровни главы {i}.',f'Complete every level in chapter {i}.',f'{i}-ci fəslin bütün səviyyələrini keç.'])
for n,r in [(1,10),(5,15),(10,25),(25,40),(50,75)]:add(f'duel_win_{n}','duels','duel_wins',n,r,'⚔️',['Первая победа' if n==1 else f'{n} побед в дуэлях','First victory' if n==1 else f'{n} duel wins','İlk qələbə' if n==1 else f'{n} duel qələbəsi'],[f'Выиграй {n} завершённых дуэлей.',f'Win {n} settled duels.',f'{n} tamamlanmış dueldə qalib gəl.'])
add('duel_draw','duels','duel_draws',1,10,'🤝',['Достойный соперник','Worthy opponent','Layiqli rəqib'],['Заверши дуэль вничью. Отменённые комнаты не считаются.','Finish a duel in a draw. Cancelled rooms do not count.','Dueli heç-heçə bitir. Ləğv edilən otaqlar sayılmır.'])
for n,r in [(10,15),(50,40)]:add(f'duel_play_{n}','duels','duel_played',n,r,'🎮',[f'{n} дуэлей',f'{n} duels',f'{n} duel'],[f'Сыграй {n} дуэлей до завершения.',f'Finish {n} duels.',f'{n} dueli sona çatdır.'])
for n,r in [(5,15),(10,30)]:add(f'duel_score_{n}','duels','duel_best',n,r,'🎯',[f'Точный ответ · {n}',f'Sharp mind · {n}',f'Dəqiq cavab · {n}'],[f'Набери {n} очков в одной завершённой дуэли.',f'Score {n} points in one settled duel.',f'Bir tamamlanmış dueldə {n} xal topla.'])
for n,r in [(5,15),(10,25),(20,40),(30,60),(45,80),(60,100),(75,125),(90,150)]:add(f'daily_streak_{n}','daily','daily_streak',n,r,'☀️',[f'{n} дней подряд',f'{n} days in a row',f'{n} gün ardıcıl'],[f'Решай загадку дня {n} дней подряд. Учитывается лучшая серия.',f'Solve the daily puzzle {n} consecutive days. Your best streak counts.',f'Günün tapmacasını {n} gün ardıcıl həll et. Ən yaxşı seriya sayılır.'])
for n,r in [(1,10),(30,30),(100,75)]:add(f'daily_total_{n}','daily','daily_total',n,r,'📅',[f'Загадки дня · {n}',f'Daily puzzles · {n}',f'Günün tapmacaları · {n}'],[f'Реши загадку дня в {n} разных днях.',f'Solve the daily puzzle on {n} different days.',f'{n} fərqli gündə günün tapmacasını həll et.'])
for n,r in [(1,10),(10,25)]:add(f'daily_first_{n}','daily','daily_first',n,r,'✨',[f'С первой попытки · {n}',f'First try · {n}',f'İlk cəhddən · {n}'],[f'В {n} разных днях реши загадку с первой попытки.',f'Solve the daily puzzle on the first attempt on {n} different days.',f'{n} fərqli gündə tapmacanı ilk cəhddən həll et.'])
themes={'sport':('⚽','Спорт','Sport','İdman'),'art':('🎨','Искусство','Art','İncəsənət'),'professions':('🧑‍💼','Профессии','Professions','Peşələr'),'travel':('🌍','Путешествия','Travel','Səyahət'),'science':('🔬','Наука','Science','Elm'),'technology':('💻','Технологии','Technology','Texnologiya'),'cinema':('🎬','Кино','Cinema','Kino'),'food':('🍽️','Еда','Food','Yemək'),'animals':('🐾','Животные','Animals','Heyvanlar'),'transport':('🚗','Транспорт','Transport','Nəqliyyat'),'home':('🏠','Дом и быт','Home','Ev və məişət'),'nature':('🌿','Природа','Nature','Təbiət')}
for id,(icon,ru,en,az) in themes.items():add(f'theme_{id}','themes',f'theme_{id}',100,30,icon,[f'Знаток: {ru}',f'Expert: {en}',f'Bilici: {az}'],[f'Пройди все 100 уровней раздела «{ru}».',f'Complete all 100 levels in {en}.',f'«{az}» bölməsinin 100 səviyyəsini keç.'])
for n,r in [(1,15),(3,30),(6,60),(12,120)]:add(f'collector_{n}','themes','themes_complete',n,r,'🏅',['Коллекционер' if n==1 else f'Коллекционер · {n}','Collector' if n==1 else f'Collector · {n}','Kolleksiyaçı' if n==1 else f'Kolleksiyaçı · {n}'],[f'Полностью заверши {n} тематических разделов.',f'Fully complete {n} themes.',f'{n} mövzu bölməsini tam bitir.'])
for n,r in [(1,10),(10,20),(50,50)]:add(f'challenge_runs_{n}','challenges','challenge_runs',n,r,'⚡',[f'Испытатель · {n}',f'Challenger · {n}',f'Sınaqçı · {n}'],[f'Заверши {n} результативных испытаний с наградой.',f'Finish {n} qualifying rewarded challenge runs.',f'{n} mükafatlı nəticəli sınağı tamamla.'])
for n,r in [(5,15),(10,30)]:add(f'challenge_streak_{n}','challenges','challenge_streak',n,r,'🔥',[f'Серия ответов · {n}',f'Answer streak · {n}',f'Cavab seriyası · {n}'],[f'Собери серию из {n} правильных ответов в одном завершённом испытании.',f'Reach a streak of {n} correct answers in a finished challenge.',f'Tamamlanmış bir sınaqda {n} düzgün cavab seriyası qur.'])
for n,r in [(10,20),(20,40)]:add(f'blitz_{n}','challenges','blitz_best',n,r,'⏱️',[f'Мастер блица · {n}',f'Blitz master · {n}',f'Blits ustası · {n}'],[f'Набери {n} очков за один завершённый блиц.',f'Score {n} points in a finished Blitz run.',f'Tamamlanmış bir blitsdə {n} xal topla.'])
Path('server/achievements/catalog.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
print(len(rows),'achievements, total rewards',sum(x['reward_coins'] for x in rows))
