
alter table public.challenge_runs
  add column if not exists language text not null default 'ru',
  add column if not exists best_streak integer not null default 0,
  add column if not exists mistakes integer not null default 0,
  add column if not exists blitz_adjustment_seconds integer not null default 0,
  add column if not exists last_answer_at timestamptz;

create table if not exists public.challenge_question_answers(
 question_id integer primary key references public.challenge_question_catalog(question_id) on delete cascade,
 answer_ru text not null, answer_en text not null, answer_az text not null
);
-- Answer rows are provisioned privately; do not add answer keys to this public migration.


create table if not exists public.challenge_run_questions(
 run_id uuid not null references public.challenge_runs(id) on delete cascade,
 seq integer not null,
 question_id integer not null references public.challenge_question_catalog(question_id),
 answered_at timestamptz,
 primary key(run_id,seq)
);
create table if not exists public.challenge_answer_attempts(
 id bigint generated by default as identity primary key,
 run_id uuid not null,
 seq integer not null,
 submitted_answer text not null,
 is_correct boolean not null,
 created_at timestamptz not null default now(),
 foreign key(run_id,seq) references public.challenge_run_questions(run_id,seq) on delete cascade
);
alter table public.challenge_question_answers enable row level security;
alter table public.challenge_run_questions enable row level security;
alter table public.challenge_answer_attempts enable row level security;
revoke all on public.challenge_question_answers,public.challenge_run_questions,public.challenge_answer_attempts from anon,authenticated,public;
grant select,insert,update,delete on public.challenge_question_answers,public.challenge_run_questions,public.challenge_answer_attempts to service_role;
grant usage,select on sequence public.challenge_answer_attempts_id_seq to service_role;

CREATE OR REPLACE FUNCTION public.reserve_challenge_questions(p_telegram_id bigint, p_run_id uuid, p_mode text, p_initial_seen integer[] DEFAULT '{}'::integer[])
 RETURNS integer[]
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare v public.players; h public.challenge_question_history; eligible integer[]; fresh integer[]; chosen integer[]; inserted integer; v_run public.challenge_runs;
begin
 select * into v from public.players where telegram_id=p_telegram_id for update;
 if v.id is null then raise exception 'player_not_found'; end if;
 select * into v_run from public.challenge_runs where id=p_run_id and player_id=v.id and mode=p_mode and finished_at is null for update;
 if v_run.id is null then raise exception 'run_not_found'; end if;
 insert into public.challenge_question_history(player_id) values(v.id) on conflict do nothing;
 get diagnostics inserted=row_count;
 select * into h from public.challenge_question_history where player_id=v.id for update;
 if inserted=1 then
  select coalesce(array_agg(distinct x),'{}'::integer[]) into h.seen from unnest(p_initial_seen) x where x between 0 and 399;
 end if;
 select array_agg(c.question_id order by c.question_id) into eligible
 from public.challenge_question_catalog c
 where not exists(select 1 from unnest(c.main_ids) n where n<=v.completed_levels)
 and not exists(select 1 from public.theme_progress p where p.player_id=v.id
   and exists(select 1 from jsonb_array_elements_text(coalesce(c.themes->p.theme_id,'[]'::jsonb)) n where n::integer=p.level_id));
 if coalesce(cardinality(eligible),0)=0 then select array_agg(question_id order by question_id) into eligible from public.challenge_question_catalog; end if;
 select array_agg(n) into fresh from unnest(eligible) n where not(n=any(h.seen));
 if coalesce(cardinality(fresh),0)=0 then h.seen:='{}';h.cycle:=h.cycle+1;fresh:=eligible;end if;
 select array_agg(n) into chosen from (select n from unnest(fresh) n order by (n is not distinct from h.last_question),random() limit 10) q;
 update public.challenge_question_history set seen=h.seen||chosen,last_question=chosen[cardinality(chosen)],cycle=h.cycle,updated_at=now() where player_id=v.id;
 insert into public.challenge_run_questions(run_id,seq,question_id)
 select p_run_id,coalesce((select max(seq)+1 from public.challenge_run_questions where run_id=p_run_id),0)+ord-1,qid
 from unnest(chosen) with ordinality as x(qid,ord);
 return chosen;
end $function$
;

create or replace function public.record_challenge_answer_server(
 p_telegram_id bigint,p_run_id uuid,p_question_id integer,p_answer text
) returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_player public.players; v_run public.challenge_runs; v_q public.challenge_run_questions;
 v_expected text; v_ok boolean; v_now timestamptz:=clock_timestamp(); v_score integer; v_streak integer;
 v_best integer; v_mistakes integer; v_adjustment integer; v_remaining bigint;
begin
 if p_answer is null or length(p_answer)>40 then raise exception 'bad_answer'; end if;
 select * into v_player from public.players where telegram_id=p_telegram_id for update;
 if v_player.id is null then raise exception 'player_not_found'; end if;
 select * into v_run from public.challenge_runs where id=p_run_id and player_id=v_player.id for update;
 if v_run.id is null then raise exception 'run_not_found'; end if;
 if v_run.finished_at is not null then raise exception 'run_finished'; end if;
 if v_run.mode not in ('limited','nohint','blitz') then raise exception 'bad_mode'; end if;
 if v_run.mode in ('limited','nohint') and v_run.mistakes>=3 then raise exception 'run_over'; end if;
 if v_run.mode='limited' and v_run.score>=10 then raise exception 'run_over'; end if;
 if v_run.last_answer_at is not null and v_now<v_run.last_answer_at+interval '150 milliseconds' then raise exception 'answer_wait'; end if;
 if v_run.mode='blitz' and v_now>=v_run.started_at+interval '60 seconds'+(v_run.blitz_adjustment_seconds*interval '1 second') then raise exception 'challenge_time_over'; end if;
 select * into v_q from public.challenge_run_questions
 where run_id=p_run_id and answered_at is null order by seq limit 1 for update;
 if v_q.run_id is null or v_q.question_id<>p_question_id then raise exception 'question_order'; end if;
 select case v_run.language when 'en' then answer_en when 'az' then answer_az else answer_ru end
 into v_expected from public.challenge_question_answers where question_id=v_q.question_id;
 if v_expected is null then raise exception 'answer_key_missing'; end if;
 v_ok:=upper(btrim(p_answer))=upper(v_expected);
 insert into public.challenge_answer_attempts(run_id,seq,submitted_answer,is_correct,created_at)
 values(p_run_id,v_q.seq,left(p_answer,40),v_ok,v_now);
 if v_ok then
   update public.challenge_run_questions set answered_at=v_now where run_id=p_run_id and seq=v_q.seq;
   v_score:=v_run.score+1; v_streak:=v_run.streak+1; v_best:=greatest(v_run.best_streak,v_streak);
   v_mistakes:=v_run.mistakes; v_adjustment:=v_run.blitz_adjustment_seconds+case when v_run.mode='blitz' then 3 else 0 end;
 else
   v_score:=v_run.score; v_streak:=0; v_best:=v_run.best_streak;
   v_mistakes:=v_run.mistakes+1; v_adjustment:=v_run.blitz_adjustment_seconds-case when v_run.mode='blitz' then 3 else 0 end;
 end if;
 update public.challenge_runs set score=v_score,streak=v_streak,best_streak=v_best,mistakes=v_mistakes,
  blitz_adjustment_seconds=v_adjustment,last_answer_at=v_now where id=p_run_id;
 if v_run.mode='blitz' then
  v_remaining:=greatest(0,floor(extract(epoch from (v_run.started_at+interval '60 seconds'+(v_adjustment*interval '1 second')-v_now))*1000)::bigint);
 else v_remaining:=null; end if;
 return jsonb_build_object('correct',v_ok,'score',v_score,'streak',v_streak,'best_streak',v_best,'mistakes',v_mistakes,'remaining_ms',v_remaining);
end $function$;
revoke all on function public.record_challenge_answer_server(bigint,uuid,integer,text) from public,anon,authenticated;
grant execute on function public.record_challenge_answer_server(bigint,uuid,integer,text) to service_role;

create or replace function public.finish_challenge_run_server(p_telegram_id bigint,p_run_id uuid,p_mode text,p_score integer,p_streak integer)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_player public.players; v_run public.challenge_runs; v_score integer; v_streak integer; v_coins integer:=0; v_xp integer:=0; v_rewarded_today integer:=0; v_elapsed numeric;
begin
 if p_mode not in ('limited','nohint','blitz') then raise exception 'bad_mode'; end if;
 select * into v_player from public.players where telegram_id=p_telegram_id for update;
 if v_player.id is null then raise exception 'player_not_found'; end if;
 select * into v_run from public.challenge_runs where id=p_run_id and player_id=v_player.id for update;
 if v_run.id is null then raise exception 'run_not_found'; end if;
 if v_run.mode<>p_mode then raise exception 'run_mode_mismatch'; end if;
 if v_run.finished_at is not null then
  select count(*) into v_rewarded_today from public.challenge_runs where player_id=v_player.id and mode=p_mode and reward_coins>0 and finished_at>=date_trunc('day',now() at time zone 'utc') at time zone 'utc';
  return jsonb_build_object('reward_coins',v_run.reward_coins,'reward_xp',v_run.reward_xp,'rewarded_runs_today',v_rewarded_today,'reward_limit',3,'duplicate',true);
 end if;
 v_score:=greatest(0,least(case when p_mode='limited' then 10 else 100 end,coalesce(v_run.score,0)));
 v_streak:=greatest(0,least(v_score,coalesce(v_run.best_streak,0)));
 v_elapsed:=extract(epoch from (clock_timestamp()-v_run.started_at));
 if p_mode='limited' then
  if v_score>=10 then v_coins:=15;v_xp:=10; elsif v_score>=7 then v_coins:=10;v_xp:=6; elsif v_score>=4 then v_coins:=5;v_xp:=3; end if;
 elsif p_mode='nohint' then
  if v_streak>=10 then v_coins:=15;v_xp:=10; elsif v_streak>=6 then v_coins:=10;v_xp:=6; elsif v_streak>=3 then v_coins:=5;v_xp:=3; end if;
 else
  if v_score>=12 then v_coins:=15;v_xp:=10; elsif v_score>=8 then v_coins:=10;v_xp:=6; elsif v_score>=5 then v_coins:=5;v_xp:=3; end if;
 end if;
 if v_elapsed<2 then v_coins:=0;v_xp:=0; end if;
 select count(*) into v_rewarded_today from public.challenge_runs where player_id=v_player.id and mode=p_mode and reward_coins>0 and finished_at>=date_trunc('day',now() at time zone 'utc') at time zone 'utc';
 if v_rewarded_today>=3 then v_coins:=0;v_xp:=0; end if;
 update public.challenge_runs set finished_at=clock_timestamp(),score=v_score,streak=v_streak,reward_coins=v_coins,reward_xp=v_xp where id=v_run.id;
 update public.challenge_profiles set
  limited_best_score=case when p_mode='limited' then greatest(limited_best_score,v_score) else limited_best_score end,
  nohint_best_streak=case when p_mode='nohint' then greatest(nohint_best_streak,v_streak) else nohint_best_streak end,
  blitz_best_score=case when p_mode='blitz' then greatest(blitz_best_score,v_score) else blitz_best_score end,
  blitz_best_streak=case when p_mode='blitz' then greatest(blitz_best_streak,v_streak) else blitz_best_streak end,
  updated_at=clock_timestamp() where player_id=v_player.id;
 if v_coins>0 or v_xp>0 then
  update public.players set coins=coins+v_coins,xp=xp+v_xp where id=v_player.id;
  if v_coins>0 then insert into public.coin_transactions(player_id,amount,transaction_type,description)
    values(v_player.id,v_coins,'challenge_reward','Challenge '||p_mode||' score '||v_score||' streak '||v_streak); end if;
  v_rewarded_today:=v_rewarded_today+1;
 end if;
 return jsonb_build_object('reward_coins',v_coins,'reward_xp',v_xp,'rewarded_runs_today',v_rewarded_today,'reward_limit',3,'duplicate',false);
end $function$;
